{{- if .Values.instance.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "devicechain.instanceNamespace" . }}
  labels:
    {{- include "devicechain.instanceLabels" . | nindent 4 }}
{{- end }}
