// Copyright The DeviceChain Authors
// SPDX-License-Identifier: Apache-2.0

package v1beta1_test

import (
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"

	"sigs.k8s.io/yaml"

	dcv1beta1 "github.com/devicechain-io/dc-k8s/api/v1beta1"
)

// These read the GENERATED manifest, which is the artifact the API server
// actually enforces. What the rules DO is tested against a real API server in
// controllers/instance_cel_test.go; a structural check cannot see whether a rule
// fires, and the first version of this file proved that by asserting a rule was
// present while the rule was bypassable.
//
// 🔴 NOTHING HERE MAY HARD-CODE THE FIELD LIST. It did, twice — once here and
// once in dcctl — and two literals maintained side by side are not two checks.
// A reviewer changed `managed` to `omitempty`, which drops it from the CRD's
// required set and lets an adopted instance be created without it and then given
// it: the exact "flipping it turns a scoped teardown into a cluster deletion"
// the rule's own message describes. Every test in this file passed. The list is
// derived from the Go type now, so the manifest is checked against the type
// rather than against a copy of the author's intent.

// specJSONFields reads the JSON names off InstanceSpec itself.
func specJSONFields(t *testing.T) []string {
	t.Helper()
	rt := reflect.TypeOf(dcv1beta1.InstanceSpec{})
	var out []string
	for i := 0; i < rt.NumField(); i++ {
		tag := rt.Field(i).Tag.Get("json")
		if tag == "" || tag == "-" {
			t.Fatalf("field %s has no json tag, so what it is called in the cluster is a guess",
				rt.Field(i).Name)
		}
		out = append(out, strings.Split(tag, ",")[0])
	}
	sort.Strings(out)
	return out
}

func loadInstanceCRD(t *testing.T) map[string]interface{} {
	t.Helper()
	path := filepath.Join("..", "..", "config", "crd", "bases", "core.devicechain.io_instances.yaml")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading the generated CRD: %v. It is generated by `make manifests`; a missing "+
			"file means the schema and the manifest have parted company", err)
	}
	var doc map[string]interface{}
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	return doc
}

// specSchema walks to the served v1beta1 spec schema.
func specSchema(t *testing.T, crd map[string]interface{}) map[string]interface{} {
	t.Helper()
	versions, _ := crd["spec"].(map[string]interface{})["versions"].([]interface{})
	for _, v := range versions {
		ver := v.(map[string]interface{})
		if ver["name"] != "v1beta1" {
			continue
		}
		props := ver["schema"].(map[string]interface{})["openAPIV3Schema"].(map[string]interface{})["properties"].(map[string]interface{})
		return props["spec"].(map[string]interface{})
	}
	t.Fatal("the CRD serves no v1beta1 version")
	return nil
}

func rulesOf(node map[string]interface{}) []string {
	raw, ok := node["x-kubernetes-validations"].([]interface{})
	if !ok {
		return nil
	}
	var out []string
	for _, r := range raw {
		if rule, ok := r.(map[string]interface{})["rule"].(string); ok {
			out = append(out, rule)
		}
	}
	return out
}

// provider and managed are required, so a field-level rule is sound on them.
// cluster is optional by design and its rule lives at the spec level; see
// TestTheClusterRuleSurvivesRemoval.
func TestTheRequiredBindingFieldsAreDeclaredImmutable(t *testing.T) {
	spec := specSchema(t, loadInstanceCRD(t))
	props := spec["properties"].(map[string]interface{})

	for _, field := range []string{"provider", "managed"} {
		node, ok := props[field].(map[string]interface{})
		if !ok {
			t.Errorf("the declaration has no %q field at all", field)
			continue
		}
		found := false
		for _, rule := range rulesOf(node) {
			if strings.Contains(strings.ReplaceAll(rule, " ", ""), "self==oldSelf") {
				found = true
			}
		}
		if !found {
			t.Errorf("%q carries no immutability rule, so a hand-edited CR could repoint this "+
				"instance's binding at another cluster", field)
		}
	}

	// The counterweight: a rule on everything would be just as wrong and would fail
	// every upgrade. imageVersion changes on any of them.
	if node, ok := props["imageVersion"].(map[string]interface{}); ok {
		for _, rule := range rulesOf(node) {
			if strings.Contains(strings.ReplaceAll(rule, " ", ""), "self==oldSelf") {
				t.Error("imageVersion is marked immutable, which would fail every upgrade")
			}
		}
	}
}

// A restore is a fact about the instance and the ordinary re-run that follows it
// restores nothing, so the naive read-modify-write would erase it.
func TestTheCRDKeepsTheRestoreFact(t *testing.T) {
	spec := specSchema(t, loadInstanceCRD(t))
	joined := strings.Join(rulesOf(spec), "\n")
	if !strings.Contains(joined, "oldSelf.restored") {
		t.Errorf("the spec carries no rule preventing restored from being unset, so an ordinary "+
			"re-run would erase it. Rules found: %q", joined)
	}
}

// The generated CRD and the Go type must describe the same object. They are
// joined by nothing but `make manifests` having been run.
func TestTheGeneratedCRDMatchesTheGoType(t *testing.T) {
	spec := specSchema(t, loadInstanceCRD(t))
	props := spec["properties"].(map[string]interface{})

	var got []string
	for k := range props {
		got = append(got, k)
	}
	sort.Strings(got)

	want := specJSONFields(t)
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("the generated CRD and the Go type describe different objects.\n"+
			"crd: %v\ntype: %v\n\nThey are joined by nothing but `make manifests` having "+
			"been run. Run it, or explain the difference.", got, want)
	}
}

// 🔴 A FIELD-LEVEL TRANSITION RULE IS ONLY SOUND ON A REQUIRED FIELD, and this
// is the property that had no test. CEL evaluates `self == oldSelf` only when the
// field is present on BOTH sides, so on an optional field the rule silently
// permits absent to value and value to absent — which is a two-edit bypass, not a
// theoretical one. Any field carrying such a rule must therefore be required, or
// the rule must live at the spec level where an object is always present.
func TestEveryFieldLevelImmutabilityRuleSitsOnARequiredField(t *testing.T) {
	spec := specSchema(t, loadInstanceCRD(t))
	props := spec["properties"].(map[string]interface{})

	required := map[string]bool{}
	if raw, ok := spec["required"].([]interface{}); ok {
		for _, r := range raw {
			required[r.(string)] = true
		}
	}

	checked := 0
	for name, node := range props {
		field, ok := node.(map[string]interface{})
		if !ok {
			continue
		}
		for _, rule := range rulesOf(field) {
			if !strings.Contains(strings.ReplaceAll(rule, " ", ""), "self==oldSelf") {
				continue
			}
			checked++
			if !required[name] {
				t.Errorf("%q carries a field-level immutability rule but is OPTIONAL. CEL skips "+
					"a transition rule whenever the field is absent on either side, so the value "+
					"can be removed and then re-set to anything — the rule's message would be "+
					"describing something it does not prevent. Make the field required, or move "+
					"the rule to the spec level where it always runs.", name)
			}
		}
	}
	if checked == 0 {
		t.Fatal("no field carries an immutability rule at all, so this test examined nothing")
	}
}

// The cluster binding must be immutable in a way that survives REMOVAL, which a
// field-level rule cannot do for an optional field. `cluster` is optional by
// design — an adopted instance has no provider-side cluster name — so its rule
// belongs at the spec level.
func TestTheClusterRuleSurvivesRemoval(t *testing.T) {
	spec := specSchema(t, loadInstanceCRD(t))
	joined := strings.Join(rulesOf(spec), "\n")
	if !strings.Contains(joined, "has(self.cluster)") || !strings.Contains(joined, "has(oldSelf.cluster)") {
		t.Errorf("the spec carries no rule comparing cluster's PRESENCE on both sides, so "+
			"removing it and setting it again would repoint the binding. Rules found: %q", joined)
	}
}
