// Copyright The DeviceChain Authors
// SPDX-License-Identifier: Apache-2.0

package v1beta1_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"sigs.k8s.io/yaml"
)

// 🔴 WHAT THIS TEST CAN AND CANNOT DO, STATED UP FRONT SO NOBODY TRUSTS IT FOR
// MORE. The CEL rules below are enforced by the API SERVER, so proving they
// behave correctly needs one — envtest, whose binaries CI does not currently
// download. A test that silently skipped without them would report success on
// every CI run while checking nothing, which is the failure this project keeps
// finding.
//
// So this asserts what it can actually see: that the rules are PRESENT, on the
// fields they belong to. That catches a marker being dropped in a refactor, which
// is the realistic way they would be lost. It does not catch a rule that is
// present and wrong.
//
// The rules are a BACKSTOP in any case. dcctl is the only supported writer of
// this object and refuses the same changes itself, in Go, with tests that do run
// (ValidateInstanceSpecChange). CEL is what stops a hand-edited CR — worth
// having, and not the primary guard.
func loadInstanceCRD(t *testing.T) map[string]interface{} {
	t.Helper()
	path := filepath.Join("..", "..", "config", "crd", "bases", "core.devicechain.io_instances.yaml")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading the generated CRD: %v. It is generated by `make manifests`; a missing "+
			"file means the schema and the manifest have parted company", err)
	}
	var doc map[string]interface{}
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	return doc
}

// specSchema walks to the served v1beta1 spec schema.
func specSchema(t *testing.T, crd map[string]interface{}) map[string]interface{} {
	t.Helper()
	versions, _ := crd["spec"].(map[string]interface{})["versions"].([]interface{})
	for _, v := range versions {
		ver := v.(map[string]interface{})
		if ver["name"] != "v1beta1" {
			continue
		}
		props := ver["schema"].(map[string]interface{})["openAPIV3Schema"].(map[string]interface{})["properties"].(map[string]interface{})
		return props["spec"].(map[string]interface{})
	}
	t.Fatal("the CRD serves no v1beta1 version")
	return nil
}

func rulesOf(node map[string]interface{}) []string {
	raw, ok := node["x-kubernetes-validations"].([]interface{})
	if !ok {
		return nil
	}
	var out []string
	for _, r := range raw {
		if rule, ok := r.(map[string]interface{})["rule"].(string); ok {
			out = append(out, rule)
		}
	}
	return out
}

// The three fields that make up the cluster binding are fixed at bootstrap,
// because `dcctl destroy` reads them to decide which cluster to act on — and, for
// `managed`, whether it may delete the cluster at all.
func TestTheClusterBindingFieldsAreDeclaredImmutable(t *testing.T) {
	spec := specSchema(t, loadInstanceCRD(t))
	props := spec["properties"].(map[string]interface{})

	for _, field := range []string{"provider", "cluster", "managed"} {
		node, ok := props[field].(map[string]interface{})
		if !ok {
			t.Errorf("the declaration has no %q field at all", field)
			continue
		}
		found := false
		for _, rule := range rulesOf(node) {
			if strings.Contains(strings.ReplaceAll(rule, " ", ""), "self==oldSelf") {
				found = true
			}
		}
		if !found {
			t.Errorf("%q carries no immutability rule, so a hand-edited CR could repoint this "+
				"instance's binding at another cluster", field)
		}
	}

	// The counterweight: a rule on everything would be just as wrong, and would
	// make every ordinary re-run fail. imageVersion changes on any upgrade.
	if node, ok := props["imageVersion"].(map[string]interface{}); ok {
		for _, rule := range rulesOf(node) {
			if strings.Contains(strings.ReplaceAll(rule, " ", ""), "self==oldSelf") {
				t.Error("imageVersion is marked immutable, which would fail every upgrade")
			}
		}
	}
}

// profile and enabledFunctionalAreas name the same set two ways, and the chart
// treats them as mutually exclusive.
func TestTheCRDRefusesBothWaysOfNamingTheAreaSet(t *testing.T) {
	spec := specSchema(t, loadInstanceCRD(t))
	joined := strings.Join(rulesOf(spec), "\n")
	if !strings.Contains(joined, "profile") || !strings.Contains(joined, "enabledFunctionalAreas") {
		t.Errorf("the spec carries no rule mentioning both profile and enabledFunctionalAreas, "+
			"so a CR naming the area set twice would be accepted. Rules found: %q", joined)
	}
}

// The generated CRD and the Go type must describe the same object. They are
// joined by nothing but `make manifests` having been run.
func TestTheGeneratedCRDMatchesTheGoType(t *testing.T) {
	spec := specSchema(t, loadInstanceCRD(t))
	props := spec["properties"].(map[string]interface{})

	want := []string{
		"cluster", "compact", "enabledFunctionalAreas", "ha", "host",
		"imageRegistry", "imageVersion", "managed", "monitoring", "profile",
		"provider", "restored", "restoredAt", "tls",
	}
	for _, f := range want {
		if _, ok := props[f]; !ok {
			t.Errorf("the generated CRD has no %q; run `make manifests`", f)
		}
	}
	if len(props) != len(want) {
		var got []string
		for k := range props {
			got = append(got, k)
		}
		t.Errorf("the generated CRD carries %d fields and the Go type %d.\ngot:  %v\nwant: %v\n"+
			"Either the manifest is stale, or a field reached the cluster without passing the "+
			"closed-list check in dcctl.", len(props), len(want), got, want)
	}
}
