apiVersion: core.devicechain.io/v1beta1
kind: InstanceConfiguration
metadata:
  name: dcic-default
spec:
  configuration:
    Infrastructure:
      Metrics:
        Enabled: true
      Nats:
        Hostname: dc-nats.dc-system
        Port: 4222
        StreamReplicas: 1
      UserManagement:
        Hostname: dc-user-management.dc-system
        Port: 8080
    Persistence:
      Rdb:
        Configuration:
          hostname: dc-postgresql.dc-system
          maxConnections: 5
          password: devicechain
          port: 5432
          username: devicechain
        Type: postgres95
      Tsdb:
        Configuration:
          hostname: dc-timescaledb-single.dc-system
          maxConnections: 5
          password: devicechain
          port: 5432
          username: postgres
        Type: timescaledb
status: {}
