#!/usr/bin/env bash
# Copyright The DeviceChain Authors
# SPDX-License-Identifier: Apache-2.0
#
# Pin the workloads each deployment profile renders.
#
# WHY THIS EXISTS
#
# The published footprint claim ("an evaluation install runs in X") is measured
# against a specific set of running services. The moment a functional area moves
# into a profile, that measurement describes something the profile no longer is —
# and nothing says so. The number does not become wrong loudly; it becomes wrong
# silently, which is worse, because it keeps getting quoted.
#
# So the profile-to-workload mapping is pinned to a golden file. Adding an area to
# a profile is fine — it just cannot be done ACCIDENTALLY, or without noticing that
# the footprint measurement now needs re-running.
#
# It renders the chart rather than reading the template's own profile dict,
# because Deployments are what consume memory, and what renders them is
# templates/deployment.yaml ranging over the resolved area list. Asserting on the
# dict would assert on our intent; asserting on the render asserts on the output.
#
# Usage:
#   hack/check-profile-workloads.sh           # verify against the golden (CI)
#   hack/check-profile-workloads.sh --update  # regenerate the golden
set -euo pipefail

cd "$(dirname "$0")/.."

CHART="deploy/helm/devicechain"
GOLDEN="hack/testdata/profile-workloads.txt"

# Every profile the chart accepts. A profile absent here renders in CI but is
# pinned by nothing, so the list is asserted against the chart's own set below
# rather than trusted.
PROFILES=(default full telemetry ingest-only)

# Render-only: never leaves this script, encrypts nothing. Required because any
# profile carrying a secret-store area (ADR-059) refuses to render without one.
key="$(openssl rand -base64 32)"

render() {
  local profile="$1"
  # The mcp area derives required URLs from the ingress, so render every profile
  # with one. Without it, `full` fails and the failure looks like a chart bug.
  helm template "$CHART" \
    --set "profile=$profile" \
    --set ingress.enabled=true \
    --set ingress.host=localhost \
    --set ingress.tls.enabled=false \
    --set "instance.config.infrastructure.secrets.rootKey=$key"
}

# The chart's own profile list, so a profile added to the chart but not to this
# script fails here instead of silently going unpinned — the same omission this
# whole check exists to prevent.
chart_profiles() {
  sed -n '/\$profiles := dict/,/^\s*-}}/p' "$CHART/templates/_helpers.tpl" \
    | grep -oE '^\s+"[a-z-]+"' \
    | tr -d ' "' \
    | sort
}

# Run at top level, never inside the process substitution below: an `exit` there
# would leave the subshell only, and the diff would still run — against nothing —
# burying this message under a spurious whole-file deletion.
check_profiles() {
  local expected actual
  expected="$(printf '%s\n' "${PROFILES[@]}" | sort)"
  actual="$(chart_profiles)"
  if [[ "$expected" != "$actual" ]]; then
    echo "error: the chart's profiles and this script's PROFILES list disagree." >&2
    diff <(echo "$expected") <(echo "$actual") >&2 || true
    echo "Add the new profile to PROFILES in $0 so it is pinned too." >&2
    exit 1
  fi
}

generate() {
  echo "# Workloads rendered per deployment profile. Generated by $0 --update."
  echo "#"
  echo "# A change here changes what an install RUNS, and therefore what it costs."
  echo "# If you are updating this file, the published footprint measurement was"
  echo "# taken against the previous set and needs re-running."
  for profile in "${PROFILES[@]}"; do
    echo
    echo "[$profile]"
    # Deployments only: they are the per-area workloads (the chart renders no
    # StatefulSets; infrastructure is OpenTofu's, outside the chart).
    render "$profile" \
      | awk '/^kind: Deployment$/{d=1;next} d&&/^  name: /{print $2; d=0}' \
      | sort
  done
}

check_profiles

if [[ "${1:-}" == "--update" ]]; then
  mkdir -p "$(dirname "$GOLDEN")"
  generate >"$GOLDEN"
  echo "wrote $GOLDEN"
  exit 0
fi

if [[ ! -f "$GOLDEN" ]]; then
  echo "error: $GOLDEN is missing; run $0 --update" >&2
  exit 1
fi

if ! diff -u "$GOLDEN" <(generate); then
  cat >&2 <<'MSG'

error: the workloads a profile renders no longer match the pinned set.

If this change is intended, run:

    hack/check-profile-workloads.sh --update

and re-run the footprint measurement — the published number was measured against
the set above, so it now describes a system that no longer exists.
MSG
  exit 1
fi

echo "profile workloads match $GOLDEN"
