#!/usr/bin/env bash
# Copyright The DeviceChain Authors
# SPDX-License-Identifier: Apache-2.0
#
# Refuses any watched secret compare — bcrypt.CompareHashAndPassword,
# subtle.ConstantTimeCompare, hmac.Equal — in production Go code outside
# backend/core/credential, unless an exemption below names the directory, the function
# AND the member, with the reason that compare is not a guessable credential check. A
# method is named Recv.Method, so an exemption for a function does not admit a method of
# the same name, nor one type's method admit another's.
# backend/core/credential is the one primitive that compares a presented secret AND
# applies its kind's policy: a per-principal backoff for passwords, and for every kind
# the dummy compare that keeps an unknown principal's timing the same.
#
# 🔴 WHY THIS IS A GATE. The login mutation and the OAuth token endpoint used to run
# their own compares with nothing counting attempts; one GraphQL request carried ~1,500
# password guesses. Moving both onto credential.Checker fixed that, and a second compare
# anywhere would quietly reopen it: calling bcrypt or subtle directly is the obvious way
# to check a secret, it compiles, it passes review, and it is unthrottled.
#
# 🔴 THE EXEMPT SET IS THE CLAIM TO READ. Every run prints each exemption with its site
# count and reason. Each one is a compare this guard was told not to report; the reason
# is the argument that it cannot be used to guess a secret. An exemption is scoped to one
# member, so a bcrypt exemption does not admit a subtle compare added to the same
# function later.
#
# ⚠️ WHAT IT DOES NOT COVER. `==` or bytes.Equal on a secret (indistinguishable from
# ordinary equality by syntax); subtle.ConstantTimeEq/ConstantTimeByteEq (integer
# compares, not watched); and a database equality lookup used as authentication — a
# device ACCESS_TOKEN is exactly that, the bearer IS the credential id, matched by
# `WHERE credential_id = ?`. This proves "no watched compare outside the primitive
# without a stated reason", not "no unthrottled credential check".
#
# It parses rather than greps, so an import alias, a call split across lines and the
# function value assigned to a variable are all caught; a dot-import of any watched
# package is refused outright. _test.go files, testdata and _legacy are skipped.
#
#   hack/check-credential-compare.sh
#   hack/check-credential-compare.sh --self-test   # prove the check can fail

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# The root and the minimum number of non-test Go files it must yield — a floor with room
# under it (backend parsed ~1,000 when this was written), so a scan that stopped reading
# the tree fails loudly instead of reporting clean.
ROOTS=(backend=400)

# The compares that are NOT a guessable credential check, each by directory, function
# (Recv.Method for a method) and member, with its reason. The guard fails if one of these matches nothing, so a
# stale entry is itself a finding, and refuses a duplicate, which could hide one.
EXEMPTIONS=(
  "backend/core/natsauth.reuseOrRehash@bcrypt.CompareHashAndPassword=decides whether a broker password hash scraped from a running cluster still matches the plaintext about to be deployed, so it can be reused rather than re-minted; the plaintext is generated by dcctl, never presented by a caller"

  # A device's MQTT password, on the ONE path that gives the sender no verdict. The MQTT
  # auth callout, which does answer, no longer reaches this function: it resolves with
  # model.ResolveDeviceCredential and compares through credential.Checker
  # (KindDeviceCredential), under a per-username backoff.
  "backend/services/device-management/model.evaluateCredential@subtle.ConstantTimeCompare=device MQTT_BASIC secret compare for per-event re-authentication only (AuthenticateDevice, from the event resolver), which gives the sender no verdict: HTTP answers 202 before resolution and an MQTT publish has no reply. The MQTT auth callout compares through credential.Checker instead. The compare is over SHA-256 digests, so it does not leak the stored secret's length"

  "backend/services/device-management/model.evaluateDeviceClaim@subtle.ConstantTimeCompare=ClaimDevice requires device:write and is bounded by the GraphQL root-field limit per request; the caller is an authenticated tenant user, not an anonymous device"

  "backend/services/device-management/model.evaluateProvisioningProfile@subtle.ConstantTimeCompare=no production caller reaches it: no provisioning transport has shipped. It must move onto credential.Checker when one does"

  "backend/services/user-management/identity.verifyPKCE@subtle.ConstantTimeCompare=not a guessing oracle: the authorization code is claimed by a revision-checked delete before the verifier is compared, so each code buys exactly one guess"

  "backend/services/user-management/identity.ServiceTokenHandler@subtle.ConstantTimeCompare=a dcctl-minted internal shared secret compared as SHA-256 digests; it cannot be guessed, so a backoff would buy nothing — the same rule that leaves OAuth client secrets unthrottled"

  "backend/core/secrets/escrow.Open@subtle.ConstantTimeCompare=integrity check: the fingerprint of a key the AEAD has already decrypted, from a local file; there is no remote caller"

  "backend/core/secrets/escrow.Artifact.Matches@subtle.ConstantTimeCompare=integrity check: fingerprint equality for a root key the operator already holds, on the operator's machine; there is no remote caller"

  "backend/cli/bootstrap.refuseRestoreOverADifferentKey@subtle.ConstantTimeCompare=operator tool: compares the deployed and the restored root keys on the operator's own machine"

  "backend/tools/drdrill.classify@subtle.ConstantTimeCompare=test instrument: the restore drill checks a decrypted plaintext against the one it seeded itself"
)

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
BIN="$TMP/credguard"

# Built from source every run, so the guard cannot drift from the rule it enforces.
go build -o "$BIN" ./backend/tools/credguard/cmd/credguard

self_test() {
  local fx="$TMP/fixtures" rc=0 must_fail=0 allowed=0 refused=0

  write() { # write <relative path> <body>
    mkdir -p "$(dirname "$fx/$1")"
    printf '%s\n' "$2" >"$fx/$1"
  }
  expect() { # expect <name> <want exit> <want text> <args...>
    local name="$1" want="$2" text="$3" out status=0
    shift 3
    case "$want" in
      0) allowed=$((allowed + 1)) ;;
      1) must_fail=$((must_fail + 1)) ;;
      2) refused=$((refused + 1)) ;;
    esac
    out="$("$BIN" "$@" 2>&1)" || status=$?
    if [ "$status" -ne "$want" ]; then
      echo "self-test: '$name' exited $status, want $want" >&2
      echo "$out" >&2
      rc=1
      return
    fi
    # Scored on CONTENT, not only the exit status: a run that exits 1 for the wrong
    # reason — a different file, a false positive — must not read as a catch.
    if [ -n "$text" ] && ! grep -qF -- "$text" <<<"$out"; then
      echo "self-test: '$name' exited $want but did not report: $text" >&2
      echo "$out" >&2
      rc=1
    fi
  }

  local BC="bcrypt.CompareHashAndPassword" ST="subtle.ConstantTimeCompare"

  # --- planted positives: each must exit 1 AND name its own file and line ---
  write direct/x.go 'package p

import "golang.org/x/crypto/bcrypt"

func f(h, s []byte) error { return bcrypt.CompareHashAndPassword(h, s) }'
  expect direct 1 "$fx/direct/x.go:5:" "$fx/direct=1"

  write linesplit/x.go 'package p

import "golang.org/x/crypto/bcrypt"

func f(h, s []byte) error {
	return bcrypt.
		CompareHashAndPassword(h, s)
}'
  expect linesplit 1 "$fx/linesplit/x.go:6:" "$fx/linesplit=1"

  write varalias/x.go 'package p

import "golang.org/x/crypto/bcrypt"

var cmp = bcrypt.CompareHashAndPassword'
  expect varalias 1 "$fx/varalias/x.go:5:" "$fx/varalias=1"

  write importalias/x.go 'package p

import b "golang.org/x/crypto/bcrypt"

func f(h, s []byte) error { return b.CompareHashAndPassword(h, s) }'
  expect importalias 1 "$fx/importalias/x.go:5:" "$fx/importalias=1"

  write twoimports/x.go 'package p

import (
	a "golang.org/x/crypto/bcrypt"
	b "golang.org/x/crypto/bcrypt"
)

var _ = b.DefaultCost

func f(h, s []byte) error { return a.CompareHashAndPassword(h, s) }'
  expect twoimports 1 "$fx/twoimports/x.go:10:" "$fx/twoimports=1"

  write dotimport/x.go 'package p

import . "golang.org/x/crypto/bcrypt"

func f(h, s []byte) error { return CompareHashAndPassword(h, s) }'
  expect dotimport 1 "$fx/dotimport/x.go:3:" "$fx/dotimport=1"

  # The constant-time class, in the same shapes.
  write subtle-direct/x.go 'package p

import "crypto/subtle"

func f(a, b []byte) bool { return subtle.ConstantTimeCompare(a, b) == 1 }'
  expect subtle-direct 1 "$fx/subtle-direct/x.go:5:" "$fx/subtle-direct=1"

  write subtle-alias/x.go 'package p

import s "crypto/subtle"

func f(a, b []byte) bool { return s.ConstantTimeCompare(a, b) == 1 }'
  expect subtle-alias 1 "$fx/subtle-alias/x.go:5:" "$fx/subtle-alias=1"

  write subtle-var/x.go 'package p

import "crypto/subtle"

var eq = subtle.ConstantTimeCompare'
  expect subtle-var 1 "$fx/subtle-var/x.go:5:" "$fx/subtle-var=1"

  write subtle-dot/x.go 'package p

import . "crypto/subtle"

func f(a, b []byte) bool { return ConstantTimeCompare(a, b) == 1 }'
  expect subtle-dot 1 "$fx/subtle-dot/x.go:3:" "$fx/subtle-dot=1"

  write hmac-direct/x.go 'package p

import "crypto/hmac"

func f(a, b []byte) bool { return hmac.Equal(a, b) }'
  expect hmac-direct 1 "$fx/hmac-direct/x.go:5:" "$fx/hmac-direct=1"

  write hmac-alias/x.go 'package p

import h "crypto/hmac"

func f(a, b []byte) bool { return h.Equal(a, b) }'
  expect hmac-alias 1 "$fx/hmac-alias/x.go:5:" "$fx/hmac-alias=1"

  write hmac-dot/x.go 'package p

import . "crypto/hmac"

func f(a, b []byte) bool { return Equal(a, b) }'
  expect hmac-dot 1 "$fx/hmac-dot/x.go:3:" "$fx/hmac-dot=1"

  # An exemption names ONE MEMBER: a subtle compare in a function exempted for bcrypt is
  # caught. Kills the mutant where exemption matching ignores the member.
  write member-scoped/backend/core/natsauth/x.go 'package natsauth

import (
	"crypto/subtle"

	"golang.org/x/crypto/bcrypt"
)

func reuseOrRehash(h, s []byte) error {
	if subtle.ConstantTimeCompare(h, s) == 1 {
		return nil
	}
	return bcrypt.CompareHashAndPassword(h, s)
}'
  expect member-scoped 1 "natsauth/x.go:10:" \
    -exempt "backend/core/natsauth.reuseOrRehash@$BC=r" "$fx/member-scoped=1"

  # The same, inside a CLOSURE: a closure is attributed to its enclosing function, which
  # is exactly where a member-agnostic match would hide a second kind of compare.
  write closure-member/backend/core/natsauth/x.go 'package natsauth

import (
	"crypto/subtle"

	"golang.org/x/crypto/bcrypt"
)

func reuseOrRehash(h, s []byte) error {
	check := func() bool { return subtle.ConstantTimeCompare(h, s) == 1 }
	_ = check
	return bcrypt.CompareHashAndPassword(h, s)
}'
  expect closure-member 1 "natsauth/x.go:10:" \
    -exempt "backend/core/natsauth.reuseOrRehash@$BC=r" "$fx/closure-member=1"

  # Two watched packages under two aliases: b is SUBTLE here, not bcrypt. Kills the mutant
  # where name resolution collapses to one map keyed on the alias alone.
  write mixed-alias/x.go 'package p

import (
	b "crypto/subtle"

	bc "golang.org/x/crypto/bcrypt"
)

var _ = bc.DefaultCost

func f(x, y []byte) bool { return b.ConstantTimeCompare(x, y) == 1 }'
  expect mixed-alias 1 "$fx/mixed-alias/x.go:11:" "$fx/mixed-alias=1"

  # The owner's SUBPACKAGES are not the owner: a compare in credentialtest is caught.
  write subpkg/backend/core/credential/credentialtest/x.go 'package credentialtest

import "golang.org/x/crypto/bcrypt"

func f(h, s []byte) error { return bcrypt.CompareHashAndPassword(h, s) }'
  expect owner-subpackage 1 "credentialtest/x.go:5:" "$fx/subpkg=1"

  # A directory whose name merely STARTS like the owner's is not the owner.
  write lookalike/backend/core/credentials/x.go 'package credentials

import "golang.org/x/crypto/bcrypt"

func f(h, s []byte) error { return bcrypt.CompareHashAndPassword(h, s) }'
  expect owner-lookalike 1 "credentials/x.go:5:" "$fx/lookalike=1"

  # An exemption names ONE function: the same compare in a sibling function is caught.
  write exemptother/backend/core/natsauth/x.go 'package natsauth

import "golang.org/x/crypto/bcrypt"

func reuseOrRehash(h, s []byte) error { return bcrypt.CompareHashAndPassword(h, s) }

func other(h, s []byte) error { return bcrypt.CompareHashAndPassword(h, s) }'
  expect exemption-other-function 1 "natsauth/x.go:7:" \
    -exempt "backend/core/natsauth.reuseOrRehash@$BC=r" "$fx/exemptother=1"

  # A stale exemption fails the run and says which.
  write stale/x.go 'package p

func f() {}'
  expect stale-exemption 1 "exemption backend/core/natsauth.reuseOrRehash@$BC matched no call site" \
    -exempt "backend/core/natsauth.reuseOrRehash@$BC=r" "$fx/stale=1"

  # An exemption for SUBTLE over a function that only calls bcrypt is stale — and the
  # bcrypt call is still a finding.
  write stale-subtle/backend/core/natsauth/x.go 'package natsauth

import "golang.org/x/crypto/bcrypt"

func reuseOrRehash(h, s []byte) error { return bcrypt.CompareHashAndPassword(h, s) }'
  expect stale-subtle 1 "exemption backend/core/natsauth.reuseOrRehash@$ST matched no call site" \
    -exempt "backend/core/natsauth.reuseOrRehash@$ST=r" "$fx/stale-subtle=1"
  expect stale-subtle-site 1 "natsauth/x.go:5:" \
    -exempt "backend/core/natsauth.reuseOrRehash@$ST=r" "$fx/stale-subtle=1"

  # An exemption names a FUNCTION, not a bare name: a method of the same name in the same
  # package is caught. Kills the mutant where the key ignores the receiver.
  write receiver-scoped/backend/core/secrets/escrow/x.go 'package escrow

import "crypto/subtle"

type Artifact struct{}

func Open(a, b []byte) bool { return subtle.ConstantTimeCompare(a, b) == 1 }

func (x *Artifact) Open(a, b []byte) bool { return subtle.ConstantTimeCompare(a, b) == 1 }'
  expect receiver-scoped 1 "escrow/x.go:9:" \
    -exempt "backend/core/secrets/escrow.Open@$ST=r" "$fx/receiver-scoped=1"

  # One type's method does not admit another type's method of the same name.
  write other-receiver/backend/core/secrets/escrow/x.go 'package escrow

import "crypto/subtle"

type Artifact struct{}
type Key struct{}

func (a *Artifact) Matches(b []byte) bool { return subtle.ConstantTimeCompare(b, b) == 1 }

func (k Key) Matches(b []byte) bool { return subtle.ConstantTimeCompare(b, b) == 1 }'
  expect other-receiver 1 "escrow/x.go:10:" \
    -exempt "backend/core/secrets/escrow.Artifact.Matches@$ST=r" "$fx/other-receiver=1"

  # --- negative controls: each must exit 0 ---
  # The same compare in a _test.go file (with a non-test file beside it for the floor).
  write testfile/x_test.go 'package p

import "golang.org/x/crypto/bcrypt"

func f(h, s []byte) error { return bcrypt.CompareHashAndPassword(h, s) }'
  write testfile/x.go 'package p'
  expect test-file 0 "" "$fx/testfile=1"

  # The same compare inside the primitive itself.
  write owner/backend/core/credential/x.go 'package credential

import "golang.org/x/crypto/bcrypt"

func f(h, s []byte) error { return bcrypt.CompareHashAndPassword(h, s) }'
  expect owner 0 "" "$fx/owner=1"

  write owner-subtle/backend/core/credential/x.go 'package credential

import "crypto/subtle"

func f(a, b []byte) bool { return subtle.ConstantTimeCompare(a, b) == 1 }'
  expect owner-subtle 0 "" "$fx/owner-subtle=1"

  # The exempted function, exempted — and the exemption printed with its count and reason.
  write exempt/backend/core/natsauth/x.go 'package natsauth

import "golang.org/x/crypto/bcrypt"

func reuseOrRehash(h, s []byte) error { return bcrypt.CompareHashAndPassword(h, s) }'
  expect exempted 0 "exempt backend/core/natsauth.reuseOrRehash@$BC (1 site(s)): the-reason" \
    -exempt "backend/core/natsauth.reuseOrRehash@$BC=the-reason" "$fx/exempt=1"

  write exempt-subtle/backend/core/secrets/escrow/x.go 'package escrow

import "crypto/subtle"

func Matches(a, b []byte) bool { return subtle.ConstantTimeCompare(a, b) == 1 }'
  expect exempt-subtle 0 "exempt backend/core/secrets/escrow.Matches@$ST (1 site(s))" \
    -exempt "backend/core/secrets/escrow.Matches@$ST=r" "$fx/exempt-subtle=1"

  # A method exempted as Recv.Method, through a pointer receiver with a type parameter.
  write exempt-method/backend/core/secrets/escrow/x.go 'package escrow

import "crypto/subtle"

type Artifact[T any] struct{}

func (a *Artifact[T]) Matches(b []byte) bool { return subtle.ConstantTimeCompare(b, b) == 1 }'
  expect exempt-method 0 "exempt backend/core/secrets/escrow.Artifact.Matches@$ST (1 site(s))" \
    -exempt "backend/core/secrets/escrow.Artifact.Matches@$ST=r" "$fx/exempt-method=1"

  # Clean code using each watched package for everything but the compare. Kills a mutant
  # that flags any selector on a watched package.
  write clean/x.go 'package p

import "golang.org/x/crypto/bcrypt"

func f(s []byte) ([]byte, error) { return bcrypt.GenerateFromPassword(s, bcrypt.DefaultCost) }'
  expect clean 0 "" "$fx/clean=1"

  write subtle-clean/x.go 'package p

import "crypto/subtle"

func f(a, b int, x, y, z []byte) int {
	subtle.XORBytes(x, y, z)
	return subtle.ConstantTimeEq(int32(a), int32(b))
}'
  expect subtle-clean 0 "" "$fx/subtle-clean=1"

  write hmac-clean/x.go 'package p

import (
	"crypto/hmac"
	"crypto/sha256"
	"hash"
)

func f(k []byte) hash.Hash { return hmac.New(sha256.New, k) }'
  expect hmac-clean 0 "" "$fx/hmac-clean=1"

  # --- the instrument: inputs it cannot use must exit 2, not report clean ---
  mkdir -p "$fx/empty"
  expect empty 2 "parsed 0 Go files" "$fx/empty=1"

  # Two identical entries would share one usage count, so one could be stale unreported.
  expect dup-exemption 2 "duplicate exemption" \
    -exempt "backend/core/natsauth.reuseOrRehash@$BC=r" \
    -exempt "backend/core/natsauth.reuseOrRehash@$BC=again" "$fx/exempt=1"

  # The old dir.func=reason form names no member, so it would admit any compare.
  expect no-member-exemption 2 "names no member" \
    -exempt "backend/core/natsauth.reuseOrRehash=r" "$fx/exempt=1"

  expect unknown-member-exemption 2 "not a watched member" \
    -exempt "backend/core/natsauth.reuseOrRehash@bytes.Equal=r" "$fx/exempt=1"

  # A function key has at most one dot (Recv.Method); anything longer names nothing.
  expect malformed-func-exemption 2 "is not dir.func@member" \
    -exempt "backend/core/secrets/escrow.A.B.C@$ST=r" "$fx/exempt=1"

  if [ "$rc" -ne 0 ]; then
    echo "self-test FAILED" >&2
    exit 1
  fi
  echo "self-test passed: $must_fail cases that must fail each reported by file and line (or stale entry)," \
    "$allowed legitimate arrangements allowed, $refused unusable inputs refused with exit 2."
}

case "${1-}" in
  --self-test)
    self_test
    exit 0
    ;;
  "") ;;
  *)
    echo "usage: $0 [--self-test]" >&2
    exit 2
    ;;
esac

args=()
for e in "${EXEMPTIONS[@]}"; do
  args+=(-exempt "$e")
done
"$BIN" "${args[@]}" "${ROOTS[@]}"
