#!/usr/bin/env bash
# Copyright The DeviceChain Authors
# SPDX-License-Identifier: Apache-2.0
#
# Refuses any bcrypt.CompareHashAndPassword in production Go code outside
# backend/core/credential — the one primitive that compares a presented secret with a
# stored hash AND counts the attempt against a per-principal backoff.
#
# 🔴 WHY THIS IS A GATE. The login mutation and the OAuth token endpoint used to run
# their own compares with nothing counting attempts; one GraphQL request carried ~1,500
# password guesses. Moving both onto credential.Checker fixed that, and a second compare
# anywhere would quietly reopen it: calling bcrypt directly is the obvious way to check a
# password, it compiles, it passes review, and it is unthrottled.
#
# ⚠️ WHAT IT DOES NOT COVER. The bcrypt class only. A credential compared another way —
# subtle.ConstantTimeCompare against a stored secret — is invisible here, and
# device-management has such checks today (claim, provisioning and device credential
# secrets). This proves "no bcrypt compare outside the primitive", not "no unthrottled
# credential check".
#
# It parses rather than greps, so an import alias, a call split across lines and the
# function value assigned to a variable are all caught; a dot-import of bcrypt is refused
# outright. _test.go files, testdata and _legacy are skipped.
#
#   hack/check-credential-compare.sh
#   hack/check-credential-compare.sh --self-test   # prove the check can fail

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# The root and the minimum number of non-test Go files it must yield — a floor with room
# under it (backend parsed ~980 when this was written), so a scan that stopped reading
# the tree fails loudly instead of reporting clean.
ROOTS=(backend=400)

# The compares that are NOT authentication, each by directory and function with its
# reason. The guard fails if one of these matches nothing, so a stale entry is itself a
# finding.
EXEMPTIONS=(
  "backend/core/natsauth.reuseOrRehash=decides whether a broker password hash scraped from a running cluster still matches the plaintext about to be deployed, so it can be reused rather than re-minted; the plaintext is generated by dcctl, never presented by a caller"
)

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
BIN="$TMP/credguard"

# Built from source every run, so the guard cannot drift from the rule it enforces.
go build -o "$BIN" ./backend/tools/credguard/cmd/credguard

self_test() {
  local fx="$TMP/fixtures" rc=0

  write() { # write <relative path> <body>
    mkdir -p "$(dirname "$fx/$1")"
    printf '%s\n' "$2" >"$fx/$1"
  }
  expect() { # expect <name> <want exit> <want text> <args...>
    local name="$1" want="$2" text="$3" out status=0
    shift 3
    out="$("$BIN" "$@" 2>&1)" || status=$?
    if [ "$status" -ne "$want" ]; then
      echo "self-test: '$name' exited $status, want $want" >&2
      echo "$out" >&2
      rc=1
      return
    fi
    # Scored on CONTENT, not only the exit status: a run that exits 1 for the wrong
    # reason — a different file, a false positive — must not read as a catch.
    if [ -n "$text" ] && ! grep -qF -- "$text" <<<"$out"; then
      echo "self-test: '$name' exited $want but did not report: $text" >&2
      echo "$out" >&2
      rc=1
    fi
  }

  # --- planted positives: each must exit 1 AND name its own file and line ---
  write direct/x.go 'package p

import "golang.org/x/crypto/bcrypt"

func f(h, s []byte) error { return bcrypt.CompareHashAndPassword(h, s) }'
  expect direct 1 "$fx/direct/x.go:5:" "$fx/direct=1"

  write linesplit/x.go 'package p

import "golang.org/x/crypto/bcrypt"

func f(h, s []byte) error {
	return bcrypt.
		CompareHashAndPassword(h, s)
}'
  expect linesplit 1 "$fx/linesplit/x.go:6:" "$fx/linesplit=1"

  write varalias/x.go 'package p

import "golang.org/x/crypto/bcrypt"

var cmp = bcrypt.CompareHashAndPassword'
  expect varalias 1 "$fx/varalias/x.go:5:" "$fx/varalias=1"

  write importalias/x.go 'package p

import b "golang.org/x/crypto/bcrypt"

func f(h, s []byte) error { return b.CompareHashAndPassword(h, s) }'
  expect importalias 1 "$fx/importalias/x.go:5:" "$fx/importalias=1"

  write twoimports/x.go 'package p

import (
	a "golang.org/x/crypto/bcrypt"
	b "golang.org/x/crypto/bcrypt"
)

var _ = b.DefaultCost

func f(h, s []byte) error { return a.CompareHashAndPassword(h, s) }'
  expect twoimports 1 "$fx/twoimports/x.go:10:" "$fx/twoimports=1"

  write dotimport/x.go 'package p

import . "golang.org/x/crypto/bcrypt"

func f(h, s []byte) error { return CompareHashAndPassword(h, s) }'
  expect dotimport 1 "$fx/dotimport/x.go:3:" "$fx/dotimport=1"

  # The owner's SUBPACKAGES are not the owner: a compare in credentialtest is caught.
  write subpkg/backend/core/credential/credentialtest/x.go 'package credentialtest

import "golang.org/x/crypto/bcrypt"

func f(h, s []byte) error { return bcrypt.CompareHashAndPassword(h, s) }'
  expect owner-subpackage 1 "credentialtest/x.go:5:" "$fx/subpkg=1"

  # A directory whose name merely STARTS like the owner's is not the owner.
  write lookalike/backend/core/credentials/x.go 'package credentials

import "golang.org/x/crypto/bcrypt"

func f(h, s []byte) error { return bcrypt.CompareHashAndPassword(h, s) }'
  expect owner-lookalike 1 "credentials/x.go:5:" "$fx/lookalike=1"

  # An exemption names ONE function: the same compare in a sibling function is caught.
  write exemptother/backend/core/natsauth/x.go 'package natsauth

import "golang.org/x/crypto/bcrypt"

func reuseOrRehash(h, s []byte) error { return bcrypt.CompareHashAndPassword(h, s) }

func other(h, s []byte) error { return bcrypt.CompareHashAndPassword(h, s) }'
  expect exemption-other-function 1 "natsauth/x.go:7:" \
    -exempt "backend/core/natsauth.reuseOrRehash=r" "$fx/exemptother=1"

  # A stale exemption fails the run and says which.
  write stale/x.go 'package p

func f() {}'
  expect stale-exemption 1 "exemption backend/core/natsauth.reuseOrRehash matched no call site" \
    -exempt "backend/core/natsauth.reuseOrRehash=r" "$fx/stale=1"

  # --- negative controls: each must exit 0 ---
  # The same compare in a _test.go file (with a non-test file beside it for the floor).
  write testfile/x_test.go 'package p

import "golang.org/x/crypto/bcrypt"

func f(h, s []byte) error { return bcrypt.CompareHashAndPassword(h, s) }'
  write testfile/x.go 'package p'
  expect test-file 0 "" "$fx/testfile=1"

  # The same compare inside the primitive itself.
  write owner/backend/core/credential/x.go 'package credential

import "golang.org/x/crypto/bcrypt"

func f(h, s []byte) error { return bcrypt.CompareHashAndPassword(h, s) }'
  expect owner 0 "" "$fx/owner=1"

  # The exempted function, exempted.
  write exempt/backend/core/natsauth/x.go 'package natsauth

import "golang.org/x/crypto/bcrypt"

func reuseOrRehash(h, s []byte) error { return bcrypt.CompareHashAndPassword(h, s) }'
  expect exempted 0 "" -exempt "backend/core/natsauth.reuseOrRehash=r" "$fx/exempt=1"

  # Clean code using bcrypt for everything but the compare.
  write clean/x.go 'package p

import "golang.org/x/crypto/bcrypt"

func f(s []byte) ([]byte, error) { return bcrypt.GenerateFromPassword(s, bcrypt.DefaultCost) }'
  expect clean 0 "" "$fx/clean=1"

  # --- the instrument: a scan that read nothing must exit 2, not report clean ---
  mkdir -p "$fx/empty"
  expect empty 2 "parsed 0 Go files" "$fx/empty=1"

  if [ "$rc" -ne 0 ]; then
    echo "self-test FAILED" >&2
    exit 1
  fi
  echo "self-test passed: 10 planted shapes caught by file and line, 4 legitimate arrangements allowed, an empty tree refused."
}

case "${1-}" in
  --self-test)
    self_test
    exit 0
    ;;
  "") ;;
  *)
    echo "usage: $0 [--self-test]" >&2
    exit 2
    ;;
esac

args=()
for e in "${EXEMPTIONS[@]}"; do
  args+=(-exempt "$e")
done
"$BIN" "${args[@]}" "${ROOTS[@]}"
