// Copyright The DeviceChain Authors
// SPDX-License-Identifier: Apache-2.0

using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using UnityEngine;
using UnityEngine.Rendering;

namespace DeviceChain.Sitepulse.Visuals
{
    /// <summary>
    /// Builds the quarry's Unity Terrain from the files <c>ArtSource/terrain/quarry_heightmap.py</c>
    /// writes: the packed 16-bit heightmap, the four terrain-layer masks and the feature file
    /// (terrain size, elevation mapping and vegetation instances).
    ///
    /// The TerrainData is made when the component is enabled, in the Editor and in a player, and
    /// is never saved as an asset: the generated files are the source, so the repository holds
    /// a 1 MB packed heightmap rather than a TerrainData asset several times that size.
    ///
    /// Steep faces (the pit's benches, the ramp walls) also get a "cliff skin": a mesh over the
    /// steep cells whose texture is projected sideways, because Terrain projects every layer from
    /// above and stretches it down a near-vertical face.
    /// </summary>
    [ExecuteAlways]
    [RequireComponent(typeof(Terrain))]
    public sealed class QuarryTerrain : MonoBehaviour
    {
        [Header("Generated by ArtSource/terrain/quarry_heightmap.py")]
        public TextAsset heightmap;
        public TextAsset features;
        [Tooltip("Masks in layer order: rock, gravel, dirt, grass.")]
        public Texture2D[] masks = new Texture2D[4];

        [Header("Look")]
        [Tooltip("Terrain layers in the same order as the masks.")]
        public TerrainLayer[] layers = new TerrainLayer[4];
        public Material terrainMaterial;
        public Material cliffMaterial;
        [Tooltip("Cells at least this steep get the cliff skin.")]
        [Range(30f, 80f)] public float cliffSlope = 46f;
        [Tooltip("World metres per repeat of the cliff texture.")]
        public float cliffTile = 8f;
        [Tooltip("Only cells within this distance of the site centre are considered for the skin.")]
        public float cliffExtent = 200f;

        [Header("Vegetation")]
        [Tooltip("Tree prototype prefabs; matched to vegetation entries by name.")]
        public GameObject[] treePrefabs = Array.Empty<GameObject>();

        [Serializable]
        public sealed class TerrainInfo
        {
            public float size_m, elev_min, elev_range, datum;
            public int height_res, splat_res;
            public float[] position;
        }

        [Serializable]
        public sealed class Plant
        {
            public string p;
            public float x, z, s, h, r;
        }

        [Serializable]
        sealed class Features
        {
            public TerrainInfo terrain;
            public Plant[] vegetation;
        }

        public TerrainInfo Info { get; private set; }
        public Terrain Terrain { get; private set; }
        public bool Built { get; private set; }

        GameObject skin;

        void OnEnable() => Build();

        void OnDisable() => Clear();

        /// <summary>(Re)build the terrain from the generated files.</summary>
        public void Build()
        {
            Clear();
            if (heightmap == null || features == null)
            {
                Debug.LogError("[quarry-terrain] heightmap and features are required");
                return;
            }
            var f = JsonUtility.FromJson<Features>(features.text);
            Info = f.terrain;
            int res = Info.height_res;
            var heights = DecodeHeights(heightmap.bytes, res);

            var td = new TerrainData { name = "Quarry (generated)", hideFlags = HideFlags.DontSave };
            td.heightmapResolution = res;
            td.size = new Vector3(Info.size_m, Info.elev_range, Info.size_m);
            td.SetHeights(0, 0, heights);

            td.terrainLayers = layers;
            td.alphamapResolution = Info.splat_res;
            td.SetAlphamaps(0, 0, ReadMasks(Info.splat_res));

            PlantTrees(td, f.vegetation);

            Terrain = GetComponent<Terrain>();
            transform.position = new Vector3(Info.position[0], Info.position[1], Info.position[2]);
            Terrain.terrainData = td;
            if (terrainMaterial != null) Terrain.materialTemplate = terrainMaterial;
            Terrain.drawInstanced = true;
            Terrain.heightmapPixelError = 3f;
            Terrain.basemapDistance = 400f;
            Terrain.treeDistance = 1200f;
            Terrain.treeLODBiasMultiplier = 1f;
            Terrain.shadowCastingMode = ShadowCastingMode.On;
            var col = GetComponent<TerrainCollider>();
            if (col != null) col.terrainData = td;

            BuildCliffSkin(heights, res);
            Built = true;
        }

        void Clear()
        {
            Built = false;
            var t = GetComponent<Terrain>();
            if (t != null && t.terrainData != null && (t.terrainData.hideFlags & HideFlags.DontSave) != 0)
            {
                var td = t.terrainData;
                t.terrainData = null;
                var col = GetComponent<TerrainCollider>();
                if (col != null) col.terrainData = null;
                DestroyImmediate(td);
            }
            if (skin != null)
            {
                var mf = skin.GetComponent<MeshFilter>();
                if (mf != null && mf.sharedMesh != null) DestroyImmediate(mf.sharedMesh);
                DestroyImmediate(skin);
                skin = null;
            }
        }

        /// <summary>
        /// Unpack the heightmap: gzip of plane-predicted uint16 samples, row 0 = south edge.
        /// Each sample was stored as s - (west + south - southwest) mod 65536.
        /// </summary>
        public static float[,] DecodeHeights(byte[] packed, int res)
        {
            var raw = new byte[res * res * 2];
            using (var gz = new GZipStream(new MemoryStream(packed), CompressionMode.Decompress))
            {
                int off = 0;
                while (off < raw.Length)
                {
                    int n = gz.Read(raw, off, raw.Length - off);
                    if (n <= 0) throw new InvalidDataException($"heightmap ends after {off} of {raw.Length} bytes");
                    off += n;
                }
            }
            var s = new int[res * res];
            for (int j = 0; j < res; j++)
            {
                for (int i = 0; i < res; i++)
                {
                    int k = j * res + i;
                    int pred = (i > 0 ? s[k - 1] : 0) + (j > 0 ? s[k - res] : 0) - (i > 0 && j > 0 ? s[k - res - 1] : 0);
                    int r = raw[2 * k] | (raw[2 * k + 1] << 8);
                    s[k] = (r + pred) & 0xFFFF;
                }
            }
            var h = new float[res, res];
            for (int j = 0; j < res; j++)
                for (int i = 0; i < res; i++)
                    h[j, i] = s[j * res + i] / 65535f;
            return h;
        }

        float[,,] ReadMasks(int res)
        {
            var maps = new float[res, res, 4];
            for (int k = 0; k < 4; k++)
            {
                var tex = masks[k];
                if (tex == null || tex.width != res || tex.height != res)
                    throw new InvalidOperationException($"mask {k} must be a readable {res}x{res} texture");
                var px = tex.GetPixels32();          // row 0 is the bottom (south) row
                for (int y = 0; y < res; y++)
                    for (int x = 0; x < res; x++)
                        maps[y, x, k] = px[y * res + x].r / 255f;
            }
            return maps;
        }

        void PlantTrees(TerrainData td, Plant[] plants)
        {
            var protos = new List<TreePrototype>();
            var index = new Dictionary<string, int>();
            foreach (var p in treePrefabs)
            {
                if (p == null) continue;
                index[p.name] = protos.Count;
                protos.Add(new TreePrototype { prefab = p });
            }
            td.treePrototypes = protos.ToArray();
            if (plants == null) return;
            var list = new List<TreeInstance>(plants.Length);
            float size = Info.size_m, x0 = Info.position[0], z0 = Info.position[2];
            foreach (var p in plants)
            {
                if (!index.TryGetValue(p.p, out int proto)) continue;
                list.Add(new TreeInstance
                {
                    prototypeIndex = proto,
                    position = new Vector3((p.x - x0) / size, 0f, (p.z - z0) / size),
                    widthScale = p.s,
                    heightScale = p.h,
                    rotation = p.r * Mathf.Deg2Rad,
                    color = Color.white,
                    lightmapColor = Color.white,
                });
            }
            td.SetTreeInstances(list.ToArray(), true);
        }

        /// <summary>
        /// A mesh over every steep heightmap cell near the site, lifted a few centimetres off the
        /// terrain, with each cell's texture projected along the axis its face points at.
        /// </summary>
        void BuildCliffSkin(float[,] h, int res)
        {
            if (cliffMaterial == null) return;
            float cell = Info.size_m / (res - 1), hy = Info.elev_range;
            float x0 = Info.position[0], y0 = Info.position[1], z0 = Info.position[2];
            float minRise = Mathf.Tan(cliffSlope * Mathf.Deg2Rad) * cell;
            int lo = Mathf.Max(0, Mathf.FloorToInt((-cliffExtent - x0) / cell));
            int hi = Mathf.Min(res - 2, Mathf.CeilToInt((cliffExtent - x0) / cell));
            var verts = new List<Vector3>();
            var uvs = new List<Vector2>();
            var norms = new List<Vector3>();
            var tris = new List<int>();
            const float lift = 0.06f;
            for (int j = lo; j <= hi; j++)
            {
                for (int i = lo; i <= hi; i++)
                {
                    float a = h[j, i] * hy, b = h[j, i + 1] * hy, c = h[j + 1, i] * hy, d = h[j + 1, i + 1] * hy;
                    float dx = (b + d - a - c) * 0.5f, dz = (c + d - a - b) * 0.5f;
                    if (Mathf.Sqrt(dx * dx + dz * dz) < minRise) continue;
                    var n = new Vector3(-dx, cell, -dz).normalized;
                    float wx = x0 + i * cell, wz = z0 + j * cell;
                    var p = new[]
                    {
                        new Vector3(wx, y0 + a, wz), new Vector3(wx + cell, y0 + b, wz),
                        new Vector3(wx, y0 + c, wz + cell), new Vector3(wx + cell, y0 + d, wz + cell),
                    };
                    int baseIndex = verts.Count;
                    bool sideX = Mathf.Abs(n.x) >= Mathf.Abs(n.z);
                    foreach (var q in p)
                    {
                        verts.Add(q + n * lift);
                        norms.Add(n);
                        uvs.Add(sideX ? new Vector2(q.z, q.y) / cliffTile : new Vector2(q.x, q.y) / cliffTile);
                    }
                    tris.Add(baseIndex); tris.Add(baseIndex + 2); tris.Add(baseIndex + 1);
                    tris.Add(baseIndex + 1); tris.Add(baseIndex + 2); tris.Add(baseIndex + 3);
                }
            }
            if (verts.Count == 0) return;
            var mesh = new Mesh { name = "QuarryCliffSkin", hideFlags = HideFlags.DontSave, indexFormat = IndexFormat.UInt32 };
            mesh.SetVertices(verts);
            mesh.SetNormals(norms);
            mesh.SetUVs(0, uvs);
            mesh.SetTriangles(tris, 0);
            mesh.RecalculateTangents();
            mesh.RecalculateBounds();
            skin = new GameObject("CliffSkin") { hideFlags = HideFlags.DontSave | HideFlags.NotEditable };
            skin.transform.SetParent(transform, false);
            skin.transform.position = Vector3.zero;
            skin.AddComponent<MeshFilter>().sharedMesh = mesh;
            var mr = skin.AddComponent<MeshRenderer>();
            mr.sharedMaterial = cliffMaterial;
            mr.shadowCastingMode = ShadowCastingMode.Off;
        }

        /// <summary>World height of the terrain surface at (x, z), or 0 before the terrain is built.</summary>
        public float HeightAt(float x, float z)
        {
            if (!Built) return 0f;
            return Terrain.SampleHeight(new Vector3(x, 0f, z)) + transform.position.y;
        }
    }
}
