// Copyright The DeviceChain Authors
// SPDX-License-Identifier: Apache-2.0

using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using UnityEngine;
using UnityEngine.Rendering;

namespace DeviceChain.Sitepulse.Visuals
{
    /// <summary>
    /// Builds the quarry's Unity Terrain from the files <c>ArtSource/terrain/quarry_heightmap.py</c>
    /// writes: the packed 16-bit heightmap, the site colour map and the feature file (terrain
    /// size, elevation mapping and vegetation instances).
    ///
    /// The TerrainData is made when the component is enabled, in the Editor and in a player, and
    /// is never saved as an asset: the generated files are the source, so the repository holds
    /// a 1 MB packed heightmap rather than a TerrainData asset several times that size.
    ///
    /// The terrain has no texture layers. Its material (<c>Sitepulse/Stylized Terrain</c>) colours
    /// the ground from the site colour map and draws rock on steep faces itself, so nothing is
    /// projected from above and stretched down a bench face.
    /// </summary>
    [ExecuteAlways]
    [RequireComponent(typeof(Terrain))]
    public sealed class QuarryTerrain : MonoBehaviour
    {
        [Header("Generated by ArtSource/terrain/quarry_heightmap.py")]
        public TextAsset heightmap;
        public TextAsset features;

        [Header("Look")]
        [Tooltip("A Sitepulse/Stylized Terrain material whose colour map is the generated quarry_color.png.")]
        public Material terrainMaterial;
        [Tooltip("Screen-space error (pixels) the terrain's level of detail allows.")]
        [Range(1f, 20f)] public float pixelError = 5f;

        [Header("Vegetation")]
        [Tooltip("Tree prototype prefabs; matched to vegetation entries by name.")]
        public GameObject[] treePrefabs = Array.Empty<GameObject>();

        [Serializable]
        public sealed class TerrainInfo
        {
            public float size_m, elev_min, elev_range, datum;
            public int height_res, color_res;
            public float[] position;
        }

        [Serializable]
        public sealed class Plant
        {
            public string p;
            public float x, z, s, h, r;
        }

        [Serializable]
        sealed class Features
        {
            public TerrainInfo terrain;
            public Plant[] vegetation;
        }

        public TerrainInfo Info { get; private set; }
        public Terrain Terrain { get; private set; }
        public bool Built { get; private set; }

        void OnEnable() => Build();

        void OnDisable() => Clear();

        /// <summary>(Re)build the terrain from the generated files.</summary>
        public void Build()
        {
            Clear();
            if (heightmap == null || features == null)
            {
                Debug.LogError("[quarry-terrain] heightmap and features are required");
                return;
            }
            var f = JsonUtility.FromJson<Features>(features.text);
            Info = f.terrain;
            int res = Info.height_res;
            var heights = DecodeHeights(heightmap.bytes, res);

            var td = new TerrainData { name = "Quarry (generated)", hideFlags = HideFlags.DontSave };
            td.heightmapResolution = res;
            td.size = new Vector3(Info.size_m, Info.elev_range, Info.size_m);
            td.SetHeights(0, 0, heights);

            PlantTrees(td, f.vegetation);

            Terrain = GetComponent<Terrain>();
            transform.position = new Vector3(Info.position[0], Info.position[1], Info.position[2]);
            Terrain.terrainData = td;
            if (terrainMaterial != null) Terrain.materialTemplate = terrainMaterial;
            Terrain.drawInstanced = true;
            Terrain.heightmapPixelError = pixelError;
            // no texture layers, so no base map: the material draws the terrain at every distance
            Terrain.basemapDistance = 20000f;
            Terrain.treeDistance = 1200f;
            Terrain.treeLODBiasMultiplier = 1f;
            Terrain.shadowCastingMode = ShadowCastingMode.On;
            var col = GetComponent<TerrainCollider>();
            if (col != null) col.terrainData = td;
            Built = true;
        }

        void Clear()
        {
            Built = false;
            var t = GetComponent<Terrain>();
            if (t != null && t.terrainData != null && (t.terrainData.hideFlags & HideFlags.DontSave) != 0)
            {
                var td = t.terrainData;
                t.terrainData = null;
                var col = GetComponent<TerrainCollider>();
                if (col != null) col.terrainData = null;
                DestroyImmediate(td);
            }
        }

        /// <summary>
        /// Unpack the heightmap: gzip of plane-predicted uint16 samples, row 0 = south edge.
        /// Each sample was stored as s - (west + south - southwest) mod 65536.
        /// </summary>
        public static float[,] DecodeHeights(byte[] packed, int res)
        {
            var raw = new byte[res * res * 2];
            using (var gz = new GZipStream(new MemoryStream(packed), CompressionMode.Decompress))
            {
                int off = 0;
                while (off < raw.Length)
                {
                    int n = gz.Read(raw, off, raw.Length - off);
                    if (n <= 0) throw new InvalidDataException($"heightmap ends after {off} of {raw.Length} bytes");
                    off += n;
                }
            }
            var s = new int[res * res];
            for (int j = 0; j < res; j++)
            {
                for (int i = 0; i < res; i++)
                {
                    int k = j * res + i;
                    int pred = (i > 0 ? s[k - 1] : 0) + (j > 0 ? s[k - res] : 0) - (i > 0 && j > 0 ? s[k - res - 1] : 0);
                    int r = raw[2 * k] | (raw[2 * k + 1] << 8);
                    s[k] = (r + pred) & 0xFFFF;
                }
            }
            var h = new float[res, res];
            for (int j = 0; j < res; j++)
                for (int i = 0; i < res; i++)
                    h[j, i] = s[j * res + i] / 65535f;
            return h;
        }

        void PlantTrees(TerrainData td, Plant[] plants)
        {
            var protos = new List<TreePrototype>();
            var index = new Dictionary<string, int>();
            foreach (var p in treePrefabs)
            {
                if (p == null) continue;
                index[p.name] = protos.Count;
                protos.Add(new TreePrototype { prefab = p });
            }
            td.treePrototypes = protos.ToArray();
            if (plants == null) return;
            var list = new List<TreeInstance>(plants.Length);
            float size = Info.size_m, x0 = Info.position[0], z0 = Info.position[2];
            foreach (var p in plants)
            {
                if (!index.TryGetValue(p.p, out int proto)) continue;
                list.Add(new TreeInstance
                {
                    prototypeIndex = proto,
                    position = new Vector3((p.x - x0) / size, 0f, (p.z - z0) / size),
                    widthScale = p.s,
                    heightScale = p.h,
                    rotation = p.r * Mathf.Deg2Rad,
                    color = Color.white,
                    lightmapColor = Color.white,
                });
            }
            td.SetTreeInstances(list.ToArray(), true);
        }

        /// <summary>World height of the terrain surface at (x, z), or 0 before the terrain is built.</summary>
        public float HeightAt(float x, float z)
        {
            if (!Built) return 0f;
            return Terrain.SampleHeight(new Vector3(x, 0f, z)) + transform.position.y;
        }
    }
}
