// Copyright The DeviceChain Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: proto/dc-device-management-events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Enumeration of failure reasons.
type FailureReason int32

const (
	FailureReason_Unknown         FailureReason = 0 // Failed for unknown reason
	FailureReason_Invalid         FailureReason = 1 // Event was not able to be parsed
	FailureReason_ApiCallFailed   FailureReason = 2 // API call required for resolution failed
	FailureReason_DeviceNotFound  FailureReason = 3 // Device token could not be resolved to a device
	FailureReason_Unauthenticated FailureReason = 4 // Presented device credential was missing or invalid (ADR-014)
)

// Enum value maps for FailureReason.
var (
	FailureReason_name = map[int32]string{
		0: "Unknown",
		1: "Invalid",
		2: "ApiCallFailed",
		3: "DeviceNotFound",
		4: "Unauthenticated",
	}
	FailureReason_value = map[string]int32{
		"Unknown":         0,
		"Invalid":         1,
		"ApiCallFailed":   2,
		"DeviceNotFound":  3,
		"Unauthenticated": 4,
	}
)

func (x FailureReason) Enum() *FailureReason {
	p := new(FailureReason)
	*p = x
	return p
}

func (x FailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dc_device_management_events_proto_enumTypes[0].Descriptor()
}

func (FailureReason) Type() protoreflect.EnumType {
	return &file_proto_dc_device_management_events_proto_enumTypes[0]
}

func (x FailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureReason.Descriptor instead.
func (FailureReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{0}
}

// *
// Event that could not be processed.
type PFailedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason  FailureReason `protobuf:"varint,1,opt,name=reason,proto3,enum=io.devicechain.devicemanagement.FailureReason" json:"reason,omitempty"`
	Service string        `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Message string        `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error   string        `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Payload []byte        `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *PFailedEvent) Reset() {
	*x = PFailedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PFailedEvent) ProtoMessage() {}

func (x *PFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PFailedEvent.ProtoReflect.Descriptor instead.
func (*PFailedEvent) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{0}
}

func (x *PFailedEvent) GetReason() FailureReason {
	if x != nil {
		return x.Reason
	}
	return FailureReason_Unknown
}

func (x *PFailedEvent) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *PFailedEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PFailedEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PFailedEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// *
// A single resolved anchor: one of the device's tracked relationships at event
// time, denormalized so the event is queryable by that (type, token) dimension
// (ADR-013/044). The target is addressed by its stable per-tenant token, not a
// device-management row id, so the reference stays valid across the service seam.
// A device with several tracked relationships yields several anchors.
type PResolvedAnchor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnchorType     string `protobuf:"bytes,1,opt,name=anchor_type,json=anchorType,proto3" json:"anchor_type,omitempty"`
	AnchorToken    string `protobuf:"bytes,2,opt,name=anchor_token,json=anchorToken,proto3" json:"anchor_token,omitempty"`
	RelationshipId uint64 `protobuf:"varint,3,opt,name=relationship_id,json=relationshipId,proto3" json:"relationship_id,omitempty"`
}

func (x *PResolvedAnchor) Reset() {
	*x = PResolvedAnchor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedAnchor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedAnchor) ProtoMessage() {}

func (x *PResolvedAnchor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedAnchor.ProtoReflect.Descriptor instead.
func (*PResolvedAnchor) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{1}
}

func (x *PResolvedAnchor) GetAnchorType() string {
	if x != nil {
		return x.AnchorType
	}
	return ""
}

func (x *PResolvedAnchor) GetAnchorToken() string {
	if x != nil {
		return x.AnchorToken
	}
	return ""
}

func (x *PResolvedAnchor) GetRelationshipId() uint64 {
	if x != nil {
		return x.RelationshipId
	}
	return 0
}

// *
// One rule-scoped dynamic-group version an event belongs to (ADR-062): the group's
// per-tenant token and the frozen selector version the membership was computed
// against. Carried on the resolved event so the DETECT engine's scope check is a set
// test on the replayed bytes (replay-correct by construction).
type PScopeMembership struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupToken string `protobuf:"bytes,1,opt,name=group_token,json=groupToken,proto3" json:"group_token,omitempty"`
	Version    int32  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *PScopeMembership) Reset() {
	*x = PScopeMembership{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PScopeMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PScopeMembership) ProtoMessage() {}

func (x *PScopeMembership) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PScopeMembership.ProtoReflect.Descriptor instead.
func (*PScopeMembership) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{2}
}

func (x *PScopeMembership) GetGroupToken() string {
	if x != nil {
		return x.GroupToken
	}
	return ""
}

func (x *PScopeMembership) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// *
// Event that was successfully resolved. It carries the full set of the device's
// tracked-relationship anchors (empty when the device is unassigned). The source
// device is addressed by its token (ADR-044): the numeric row id never crosses the
// seam to event-management / device-state.
//
// device_type_token and profile_version_token denormalize the device's rule-scoping
// identity at resolve time (ADR-051): the device-type token and a
// "{profileToken}@{version}" token naming the active PUBLISHED profile version
// (ADR-045) whose rules apply. event-processing's DETECT engine selects which
// rules apply to an event from these tokens without a graph read back into
// device-management. profile_version_token is empty when the type has no profile
// or the profile is unpublished (no active version) — the device has no resolvable
// rules, the same limiting case as an unclassified measurement.
type PResolvedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source              string             `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	AltId               *string            `protobuf:"bytes,2,opt,name=alt_id,json=altId,proto3,oneof" json:"alt_id,omitempty"`
	SourceDeviceToken   string             `protobuf:"bytes,3,opt,name=source_device_token,json=sourceDeviceToken,proto3" json:"source_device_token,omitempty"`
	Anchors             []*PResolvedAnchor `protobuf:"bytes,4,rep,name=anchors,proto3" json:"anchors,omitempty"`
	OccurredTime        string             `protobuf:"bytes,7,opt,name=occurred_time,json=occurredTime,proto3" json:"occurred_time,omitempty"`
	ProcessedTime       string             `protobuf:"bytes,8,opt,name=processed_time,json=processedTime,proto3" json:"processed_time,omitempty"`
	EventType           int64              `protobuf:"varint,9,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload             []byte             `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	DeviceTypeToken     *string            `protobuf:"bytes,11,opt,name=device_type_token,json=deviceTypeToken,proto3,oneof" json:"device_type_token,omitempty"`
	ProfileVersionToken *string            `protobuf:"bytes,12,opt,name=profile_version_token,json=profileVersionToken,proto3,oneof" json:"profile_version_token,omitempty"`
	// The rule-scoped dynamic-group versions the device + its anchors belong to
	// (ADR-062), stamped at resolve time; empty when no rule references such a group.
	ScopeMemberships []*PScopeMembership `protobuf:"bytes,13,rep,name=scope_memberships,json=scopeMemberships,proto3" json:"scope_memberships,omitempty"`
}

func (x *PResolvedEvent) Reset() {
	*x = PResolvedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedEvent) ProtoMessage() {}

func (x *PResolvedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedEvent.ProtoReflect.Descriptor instead.
func (*PResolvedEvent) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{3}
}

func (x *PResolvedEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PResolvedEvent) GetAltId() string {
	if x != nil && x.AltId != nil {
		return *x.AltId
	}
	return ""
}

func (x *PResolvedEvent) GetSourceDeviceToken() string {
	if x != nil {
		return x.SourceDeviceToken
	}
	return ""
}

func (x *PResolvedEvent) GetAnchors() []*PResolvedAnchor {
	if x != nil {
		return x.Anchors
	}
	return nil
}

func (x *PResolvedEvent) GetOccurredTime() string {
	if x != nil {
		return x.OccurredTime
	}
	return ""
}

func (x *PResolvedEvent) GetProcessedTime() string {
	if x != nil {
		return x.ProcessedTime
	}
	return ""
}

func (x *PResolvedEvent) GetEventType() int64 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *PResolvedEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PResolvedEvent) GetDeviceTypeToken() string {
	if x != nil && x.DeviceTypeToken != nil {
		return *x.DeviceTypeToken
	}
	return ""
}

func (x *PResolvedEvent) GetProfileVersionToken() string {
	if x != nil && x.ProfileVersionToken != nil {
		return *x.ProfileVersionToken
	}
	return ""
}

func (x *PResolvedEvent) GetScopeMemberships() []*PScopeMembership {
	if x != nil {
		return x.ScopeMemberships
	}
	return nil
}

// *
// Payload for resolved new relationship request. The target is a uniform
// (type, id) reference (ADR-013).
type PResolvedNewRelationshipPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RelationshipTypeId uint64  `protobuf:"varint,1,opt,name=relationship_type_id,json=relationshipTypeId,proto3" json:"relationship_type_id,omitempty"`
	TargetType         *string `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3,oneof" json:"target_type,omitempty"`
	TargetId           *uint64 `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3,oneof" json:"target_id,omitempty"`
}

func (x *PResolvedNewRelationshipPayload) Reset() {
	*x = PResolvedNewRelationshipPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedNewRelationshipPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedNewRelationshipPayload) ProtoMessage() {}

func (x *PResolvedNewRelationshipPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedNewRelationshipPayload.ProtoReflect.Descriptor instead.
func (*PResolvedNewRelationshipPayload) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{4}
}

func (x *PResolvedNewRelationshipPayload) GetRelationshipTypeId() uint64 {
	if x != nil {
		return x.RelationshipTypeId
	}
	return 0
}

func (x *PResolvedNewRelationshipPayload) GetTargetType() string {
	if x != nil && x.TargetType != nil {
		return *x.TargetType
	}
	return ""
}

func (x *PResolvedNewRelationshipPayload) GetTargetId() uint64 {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return 0
}

// *
// Single location entry for a location payload.
type PResolvedLocationEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude     *string `protobuf:"bytes,1,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude    *string `protobuf:"bytes,2,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	Elevation    *string `protobuf:"bytes,3,opt,name=elevation,proto3,oneof" json:"elevation,omitempty"`
	OccurredTime *string `protobuf:"bytes,4,opt,name=occurred_time,json=occurredTime,proto3,oneof" json:"occurred_time,omitempty"`
}

func (x *PResolvedLocationEntry) Reset() {
	*x = PResolvedLocationEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedLocationEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedLocationEntry) ProtoMessage() {}

func (x *PResolvedLocationEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedLocationEntry.ProtoReflect.Descriptor instead.
func (*PResolvedLocationEntry) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{5}
}

func (x *PResolvedLocationEntry) GetLatitude() string {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return ""
}

func (x *PResolvedLocationEntry) GetLongitude() string {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return ""
}

func (x *PResolvedLocationEntry) GetElevation() string {
	if x != nil && x.Elevation != nil {
		return *x.Elevation
	}
	return ""
}

func (x *PResolvedLocationEntry) GetOccurredTime() string {
	if x != nil && x.OccurredTime != nil {
		return *x.OccurredTime
	}
	return ""
}

// *
// Payload for a location event.
type PResolvedLocationsPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*PResolvedLocationEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *PResolvedLocationsPayload) Reset() {
	*x = PResolvedLocationsPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedLocationsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedLocationsPayload) ProtoMessage() {}

func (x *PResolvedLocationsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedLocationsPayload.ProtoReflect.Descriptor instead.
func (*PResolvedLocationsPayload) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{6}
}

func (x *PResolvedLocationsPayload) GetEntries() []*PResolvedLocationEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// *
// Single measurement entry for a measurement payload. unit and data_type are
// denormalized from the bound metric definition at resolve time (ADR-016) — as of
// the profile's active PUBLISHED version, alongside the classifier — so the stored
// measurement is self-describing on read without a cross-service hop back into
// device-management, and stays consistent for historical rows across a later
// republish. Both are absent for an undeclared (unbound) measurement.
type PResolvedMeasurementEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value      string  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Classifier *uint64 `protobuf:"varint,3,opt,name=classifier,proto3,oneof" json:"classifier,omitempty"`
	Unit       *string `protobuf:"bytes,4,opt,name=unit,proto3,oneof" json:"unit,omitempty"`
	DataType   *string `protobuf:"bytes,5,opt,name=data_type,json=dataType,proto3,oneof" json:"data_type,omitempty"`
}

func (x *PResolvedMeasurementEntry) Reset() {
	*x = PResolvedMeasurementEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedMeasurementEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedMeasurementEntry) ProtoMessage() {}

func (x *PResolvedMeasurementEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedMeasurementEntry.ProtoReflect.Descriptor instead.
func (*PResolvedMeasurementEntry) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{7}
}

func (x *PResolvedMeasurementEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PResolvedMeasurementEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PResolvedMeasurementEntry) GetClassifier() uint64 {
	if x != nil && x.Classifier != nil {
		return *x.Classifier
	}
	return 0
}

func (x *PResolvedMeasurementEntry) GetUnit() string {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return ""
}

func (x *PResolvedMeasurementEntry) GetDataType() string {
	if x != nil && x.DataType != nil {
		return *x.DataType
	}
	return ""
}

// *
// Single measurement entry for a measurement payload.
type PResolvedMeasurementsEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Measurements []*PResolvedMeasurementEntry `protobuf:"bytes,1,rep,name=measurements,proto3" json:"measurements,omitempty"`
	OccurredTime *string                      `protobuf:"bytes,2,opt,name=occurred_time,json=occurredTime,proto3,oneof" json:"occurred_time,omitempty"`
}

func (x *PResolvedMeasurementsEntry) Reset() {
	*x = PResolvedMeasurementsEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedMeasurementsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedMeasurementsEntry) ProtoMessage() {}

func (x *PResolvedMeasurementsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedMeasurementsEntry.ProtoReflect.Descriptor instead.
func (*PResolvedMeasurementsEntry) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{8}
}

func (x *PResolvedMeasurementsEntry) GetMeasurements() []*PResolvedMeasurementEntry {
	if x != nil {
		return x.Measurements
	}
	return nil
}

func (x *PResolvedMeasurementsEntry) GetOccurredTime() string {
	if x != nil && x.OccurredTime != nil {
		return *x.OccurredTime
	}
	return ""
}

// *
// Payload for a measurement event.
type PResolvedMeasurementsPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*PResolvedMeasurementsEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *PResolvedMeasurementsPayload) Reset() {
	*x = PResolvedMeasurementsPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedMeasurementsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedMeasurementsPayload) ProtoMessage() {}

func (x *PResolvedMeasurementsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedMeasurementsPayload.ProtoReflect.Descriptor instead.
func (*PResolvedMeasurementsPayload) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{9}
}

func (x *PResolvedMeasurementsPayload) GetEntries() []*PResolvedMeasurementsEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// *
// Single alert entry for an alerts payload.
type PResolvedAlertEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         string  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Level        uint32  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Message      string  `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Source       string  `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	OccurredTime *string `protobuf:"bytes,5,opt,name=occurred_time,json=occurredTime,proto3,oneof" json:"occurred_time,omitempty"`
}

func (x *PResolvedAlertEntry) Reset() {
	*x = PResolvedAlertEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedAlertEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedAlertEntry) ProtoMessage() {}

func (x *PResolvedAlertEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedAlertEntry.ProtoReflect.Descriptor instead.
func (*PResolvedAlertEntry) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{10}
}

func (x *PResolvedAlertEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PResolvedAlertEntry) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PResolvedAlertEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PResolvedAlertEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PResolvedAlertEntry) GetOccurredTime() string {
	if x != nil && x.OccurredTime != nil {
		return *x.OccurredTime
	}
	return ""
}

// *
// Payload for an alert event.
type PResolvedAlertsPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*PResolvedAlertEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *PResolvedAlertsPayload) Reset() {
	*x = PResolvedAlertsPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedAlertsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedAlertsPayload) ProtoMessage() {}

func (x *PResolvedAlertsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedAlertsPayload.ProtoReflect.Descriptor instead.
func (*PResolvedAlertsPayload) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{11}
}

func (x *PResolvedAlertsPayload) GetEntries() []*PResolvedAlertEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// *
// Alarm state-change event (ADR-041): re-emitted whenever a raised alarm
// transitions (raised/escalated/de-escalated/cleared/acknowledged). It is a
// snapshot of the alarm after the transition plus the transition kind and the
// prior severity (for a severity change), and is the substrate for graphql-ws
// subscriptions (ADR-037) and notifications (ADR-017).
type PAlarmStateChangeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType        string   `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	AlarmToken       string   `protobuf:"bytes,2,opt,name=alarm_token,json=alarmToken,proto3" json:"alarm_token,omitempty"`
	OriginatorType   string   `protobuf:"bytes,3,opt,name=originator_type,json=originatorType,proto3" json:"originator_type,omitempty"`
	OriginatorId     uint64   `protobuf:"varint,4,opt,name=originator_id,json=originatorId,proto3" json:"originator_id,omitempty"`
	AlarmKey         string   `protobuf:"bytes,5,opt,name=alarm_key,json=alarmKey,proto3" json:"alarm_key,omitempty"`
	MetricKey        string   `protobuf:"bytes,6,opt,name=metric_key,json=metricKey,proto3" json:"metric_key,omitempty"`
	State            string   `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	Severity         string   `protobuf:"bytes,8,opt,name=severity,proto3" json:"severity,omitempty"`
	Acknowledged     bool     `protobuf:"varint,9,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	PreviousSeverity *string  `protobuf:"bytes,10,opt,name=previous_severity,json=previousSeverity,proto3,oneof" json:"previous_severity,omitempty"`
	AcknowledgedBy   *string  `protobuf:"bytes,11,opt,name=acknowledged_by,json=acknowledgedBy,proto3,oneof" json:"acknowledged_by,omitempty"`
	LastValue        *float64 `protobuf:"fixed64,12,opt,name=last_value,json=lastValue,proto3,oneof" json:"last_value,omitempty"`
	Message          *string  `protobuf:"bytes,13,opt,name=message,proto3,oneof" json:"message,omitempty"`
	OccurredTime     string   `protobuf:"bytes,14,opt,name=occurred_time,json=occurredTime,proto3" json:"occurred_time,omitempty"`
	RaisedTime       string   `protobuf:"bytes,15,opt,name=raised_time,json=raisedTime,proto3" json:"raised_time,omitempty"`
}

func (x *PAlarmStateChangeEvent) Reset() {
	*x = PAlarmStateChangeEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PAlarmStateChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PAlarmStateChangeEvent) ProtoMessage() {}

func (x *PAlarmStateChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PAlarmStateChangeEvent.ProtoReflect.Descriptor instead.
func (*PAlarmStateChangeEvent) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{12}
}

func (x *PAlarmStateChangeEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetAlarmToken() string {
	if x != nil {
		return x.AlarmToken
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetOriginatorType() string {
	if x != nil {
		return x.OriginatorType
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetOriginatorId() uint64 {
	if x != nil {
		return x.OriginatorId
	}
	return 0
}

func (x *PAlarmStateChangeEvent) GetAlarmKey() string {
	if x != nil {
		return x.AlarmKey
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetMetricKey() string {
	if x != nil {
		return x.MetricKey
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *PAlarmStateChangeEvent) GetPreviousSeverity() string {
	if x != nil && x.PreviousSeverity != nil {
		return *x.PreviousSeverity
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetAcknowledgedBy() string {
	if x != nil && x.AcknowledgedBy != nil {
		return *x.AcknowledgedBy
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetLastValue() float64 {
	if x != nil && x.LastValue != nil {
		return *x.LastValue
	}
	return 0
}

func (x *PAlarmStateChangeEvent) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetOccurredTime() string {
	if x != nil {
		return x.OccurredTime
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetRaisedTime() string {
	if x != nil {
		return x.RaisedTime
	}
	return ""
}

// *
// Entity-deletion event (ADR-044): emitted when an edge entity is deleted in
// device-management so cross-service reference holders (event-management's
// event_anchors) can drop dangling references. The entity is named by both its
// uniform (type, token) address (ADR-013/042) and its raw row id — the id is what
// event_anchors currently key on, the token is for logging and the future
// token-reference reshape (ADR-044 decision 4). The tenant travels on the subject,
// not in the payload.
type PEntityDeletedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityType  string `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId    uint64 `protobuf:"varint,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityToken string `protobuf:"bytes,3,opt,name=entity_token,json=entityToken,proto3" json:"entity_token,omitempty"`
	DeletedTime string `protobuf:"bytes,4,opt,name=deleted_time,json=deletedTime,proto3" json:"deleted_time,omitempty"`
}

func (x *PEntityDeletedEvent) Reset() {
	*x = PEntityDeletedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PEntityDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PEntityDeletedEvent) ProtoMessage() {}

func (x *PEntityDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PEntityDeletedEvent.ProtoReflect.Descriptor instead.
func (*PEntityDeletedEvent) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{13}
}

func (x *PEntityDeletedEvent) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *PEntityDeletedEvent) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *PEntityDeletedEvent) GetEntityToken() string {
	if x != nil {
		return x.EntityToken
	}
	return ""
}

func (x *PEntityDeletedEvent) GetDeletedTime() string {
	if x != nil {
		return x.DeletedTime
	}
	return ""
}

// *
// One published detection rule inside a PDetectionRulesPublishedEvent: its
// authoring token (unique per profile, ADR-042) plus the opaque rules.Rule JSON
// document (ADR-051 slice 4b-1). device-management never parses the definition
// taxonomy — it is compiled by event-processing's single-homed DETECT compiler on
// consume, the same compiler the ADR-044 publish gate ran (slice 4b-2).
type PPublishedDetectionRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token      string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Definition string `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	// Optional group scope (ADR-062 S4): the published dynamic entity-group version
	// whose members the rule fires for. Empty token / version 0 ⇒ an unscoped
	// (profile-wide) rule; a non-empty token ⇒ the engine fires the rule only for events
	// whose scope_memberships include {entity_group_token}@{entity_group_version}.
	EntityGroupToken   string `protobuf:"bytes,3,opt,name=entity_group_token,json=entityGroupToken,proto3" json:"entity_group_token,omitempty"`
	EntityGroupVersion int32  `protobuf:"varint,4,opt,name=entity_group_version,json=entityGroupVersion,proto3" json:"entity_group_version,omitempty"`
}

func (x *PPublishedDetectionRule) Reset() {
	*x = PPublishedDetectionRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PPublishedDetectionRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PPublishedDetectionRule) ProtoMessage() {}

func (x *PPublishedDetectionRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PPublishedDetectionRule.ProtoReflect.Descriptor instead.
func (*PPublishedDetectionRule) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{14}
}

func (x *PPublishedDetectionRule) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PPublishedDetectionRule) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *PPublishedDetectionRule) GetEntityGroupToken() string {
	if x != nil {
		return x.EntityGroupToken
	}
	return ""
}

func (x *PPublishedDetectionRule) GetEntityGroupVersion() int32 {
	if x != nil {
		return x.EntityGroupVersion
	}
	return 0
}

// *
// Detection-rules-published event (ADR-051 slice 4b-3): emitted post-commit when a
// device profile is published, carrying the ENABLED detection rules frozen into the
// new immutable version so event-processing's DETECT engine can run them. The rules
// are keyed on the immutable profile_version_token ("{profileToken}@{version}",
// ADR-045) — the same token a resolved event denormalizes (PResolvedEvent field 12) —
// so the engine scopes them read-free and a rollback needs no new fact (the target
// version's rules are already loaded). Disabled rules are omitted: they ride the
// frozen snapshot but are inert until a later publish enables them. The tenant travels
// on the per-tenant subject, not in the payload.
type PDetectionRulesPublishedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProfileVersionToken string                     `protobuf:"bytes,1,opt,name=profile_version_token,json=profileVersionToken,proto3" json:"profile_version_token,omitempty"`
	Rules               []*PPublishedDetectionRule `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	PublishedAt         string                     `protobuf:"bytes,3,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
}

func (x *PDetectionRulesPublishedEvent) Reset() {
	*x = PDetectionRulesPublishedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PDetectionRulesPublishedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDetectionRulesPublishedEvent) ProtoMessage() {}

func (x *PDetectionRulesPublishedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDetectionRulesPublishedEvent.ProtoReflect.Descriptor instead.
func (*PDetectionRulesPublishedEvent) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{15}
}

func (x *PDetectionRulesPublishedEvent) GetProfileVersionToken() string {
	if x != nil {
		return x.ProfileVersionToken
	}
	return ""
}

func (x *PDetectionRulesPublishedEvent) GetRules() []*PPublishedDetectionRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *PDetectionRulesPublishedEvent) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

// *
// Device-roster event (ADR-051 slice 4c-2): emitted post-commit when a device is
// created or re-typed, naming the device and the STABLE profile token its type
// adopts (ADR-045) — deliberately the profile token, not the "{profileToken}@{version}"
// token, so a re-publish that mints a new version never staleness-orphans the roster
// entry (event-processing cross-references the latest published version at arming
// time). expected_since is the device's creation time: the base of the dead-man clock
// for a device that has NEVER reported, so event-processing can arm absence for it
// (the reported-once-then-silent case is already covered by the heartbeat-armed timer).
// profile_token is empty when the type has no profile — a roster entry with no
// resolvable rules, retained so a later re-type re-homes it. The tenant travels on the
// per-tenant subject, not in the payload.
type PDeviceRosterEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceToken   string `protobuf:"bytes,1,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	ProfileToken  string `protobuf:"bytes,2,opt,name=profile_token,json=profileToken,proto3" json:"profile_token,omitempty"`
	ExpectedSince string `protobuf:"bytes,3,opt,name=expected_since,json=expectedSince,proto3" json:"expected_since,omitempty"`
}

func (x *PDeviceRosterEvent) Reset() {
	*x = PDeviceRosterEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PDeviceRosterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDeviceRosterEvent) ProtoMessage() {}

func (x *PDeviceRosterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDeviceRosterEvent.ProtoReflect.Descriptor instead.
func (*PDeviceRosterEvent) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{16}
}

func (x *PDeviceRosterEvent) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *PDeviceRosterEvent) GetProfileToken() string {
	if x != nil {
		return x.ProfileToken
	}
	return ""
}

func (x *PDeviceRosterEvent) GetExpectedSince() string {
	if x != nil {
		return x.ExpectedSince
	}
	return ""
}

// *
// Device-attribute event (ADR-051 slice 4c-3): emitted post-commit when a numeric,
// platform-set attribute of a DEVICE is upserted or deleted, so event-processing can
// resolve a DYNAMIC detection threshold from it — a rule of the form
// "m[metric] <op> attr[key]" reads the device's own attribute instead of a
// compile-time literal, so one published rule enforces a per-device limit. Only
// numeric device attributes (ADR-012 value type DOUBLE or LONG) in the two
// platform-set scopes (SHARED or SERVER) are emitted: CLIENT (device-reported) is
// excluded so a device cannot set the limit it is checked against. A non-numeric
// value or type emits a removal (removed=true) so a previously-projected numeric value
// never goes stale, as does an attribute delete. value is the parsed number (unset
// when removed). updated_at is the write time — the monotonic clock event-processing
// orders upsert-vs-delete on.
//
// scope is part of the identity: an attribute's natural key is (entity, scope, key), so
// a device may hold the SAME key in both eligible scopes at once. The fact therefore
// carries scope, and event-processing keys its projection on (device, scope, key) so a
// write/delete in one scope never annihilates the other. The rule language stays
// scope-less (attr["key"]); event-processing flattens the two scopes at eval time with a
// fixed precedence — SERVER over SHARED (a platform-only override beats the
// device-readable value). The tenant travels on the per-tenant subject, not in the
// payload.
//
// A device DELETE emits NO attribute fact (its attributes are hard-deleted in the delete
// cascade); event-processing drops the device's whole attribute projection off the
// entity-deleted fact instead, exactly as the device roster does.
type PDeviceAttributeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceToken string  `protobuf:"bytes,1,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	AttrKey     string  `protobuf:"bytes,2,opt,name=attr_key,json=attrKey,proto3" json:"attr_key,omitempty"`
	Scope       string  `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Value       float64 `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	Removed     bool    `protobuf:"varint,5,opt,name=removed,proto3" json:"removed,omitempty"`
	UpdatedAt   string  `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *PDeviceAttributeEvent) Reset() {
	*x = PDeviceAttributeEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PDeviceAttributeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDeviceAttributeEvent) ProtoMessage() {}

func (x *PDeviceAttributeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDeviceAttributeEvent.ProtoReflect.Descriptor instead.
func (*PDeviceAttributeEvent) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{17}
}

func (x *PDeviceAttributeEvent) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *PDeviceAttributeEvent) GetAttrKey() string {
	if x != nil {
		return x.AttrKey
	}
	return ""
}

func (x *PDeviceAttributeEvent) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *PDeviceAttributeEvent) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *PDeviceAttributeEvent) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

func (x *PDeviceAttributeEvent) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_proto_dc_device_management_events_proto protoreflect.FileDescriptor

var file_proto_dc_device_management_events_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x63, 0x2d, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x69, 0x6f, 0x2e, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xba, 0x01, 0x0a, 0x0c, 0x50,
	0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x46, 0x0a, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e, 0x2e, 0x69, 0x6f,
	0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x61,
	0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x7e, 0x0a, 0x0f, 0x50, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x64, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6e,
	0x63, 0x68, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x6e, 0x63, 0x68, 0x6f, 0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x27,
	0x0a, 0x0f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x68, 0x69, 0x70, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x10, 0x50, 0x53, 0x63, 0x6f, 0x70,
	0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xee, 0x04, 0x0a, 0x0e, 0x50, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x1a, 0x0a, 0x06, 0x61, 0x6c, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x05, 0x61, 0x6c, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x2e, 0x0a,
	0x13, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x4a, 0x0a,
	0x07, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30,
	0x2e, 0x69, 0x6f, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x50, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72,
	0x52, 0x07, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x63, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x25,
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2f,
	0x0a, 0x11, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0f, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x12,
	0x37, 0x0a, 0x15, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02,
	0x52, 0x13, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x5e, 0x0a, 0x11, 0x73, 0x63, 0x6f, 0x70,
	0x65, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x73, 0x18, 0x0d, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x69, 0x6f, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x10, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x61, 0x6c, 0x74,
	0x5f, 0x69, 0x64, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x18, 0x0a, 0x16, 0x5f, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x4a, 0x04, 0x08, 0x05, 0x10, 0x06, 0x4a, 0x04, 0x08, 0x06, 0x10, 0x07, 0x52,
	0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x52, 0x09, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x22, 0xb9, 0x01, 0x0a, 0x1f, 0x50, 0x52, 0x65, 0x73,
	0x6f, 0x6c, 0x76, 0x65, 0x64, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x68, 0x69, 0x70, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x30, 0x0a, 0x14, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x12, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a,
	0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x48, 0x01, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x5f, 0x69, 0x64, 0x22, 0xe4, 0x01, 0x0a, 0x16, 0x50, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65,
	0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1f,
	0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x21, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x65, 0x6c, 0x65, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x09, 0x65, 0x6c, 0x65, 0x76, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x28, 0x0a, 0x0d, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x0c,
	0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42,
	0x0b, 0x0a, 0x09, 0x5f, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x42, 0x0c, 0x0a, 0x0a,
	0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x65,
	0x6c, 0x65, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x6f, 0x63, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x6e, 0x0a, 0x19, 0x50, 0x52,
	0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x51, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x69, 0x6f, 0x2e, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0xcb, 0x01, 0x0a, 0x19, 0x50,
	0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x23, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x88, 0x01, 0x01,
	0x12, 0x20, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x88,
	0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0xb8, 0x01, 0x0a, 0x1a, 0x50, 0x52, 0x65,
	0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x5e, 0x0a, 0x0c, 0x6d, 0x65, 0x61, 0x73, 0x75,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3a, 0x2e,
	0x69, 0x6f, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x50, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x6d, 0x65, 0x61, 0x73, 0x75,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x28, 0x0a, 0x0d, 0x6f, 0x63, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x0c, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x88, 0x01,
	0x01, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x22, 0x75, 0x0a, 0x1c, 0x50, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64,
	0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x55, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x69, 0x6f, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64,
	0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0xad, 0x01, 0x0a, 0x13, 0x50,
	0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x28,
	0x0a, 0x0d, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x6f, 0x63, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x68, 0x0a, 0x16, 0x50, 0x52,
	0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x4e, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x69, 0x6f, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65,
	0x64, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x22, 0xe6, 0x04, 0x0a, 0x16, 0x50, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x27, 0x0a, 0x0f, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x61,
	0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0c, 0x61, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x64, 0x12,
	0x30, 0x0a, 0x11, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x5f, 0x73, 0x65, 0x76, 0x65,
	0x72, 0x69, 0x74, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x10, 0x70, 0x72,
	0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x88, 0x01,
	0x01, 0x12, 0x2c, 0x0a, 0x0f, 0x61, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x64, 0x5f, 0x62, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0e, 0x61, 0x63,
	0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x64, 0x42, 0x79, 0x88, 0x01, 0x01, 0x12,
	0x22, 0x0a, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x01, 0x48, 0x02, 0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x63, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x61, 0x69, 0x73, 0x65,
	0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x61,
	0x69, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x70, 0x72, 0x65,
	0x76, 0x69, 0x6f, 0x75, 0x73, 0x5f, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x42, 0x12,
	0x0a, 0x10, 0x5f, 0x61, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x64, 0x5f,
	0x62, 0x79, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x99, 0x01,
	0x0a, 0x13, 0x50, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xaf, 0x01, 0x0a, 0x17, 0x50, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x12, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x30, 0x0a, 0x14, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xc6, 0x01, 0x0a, 0x1d,
	0x50, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x32, 0x0a,
	0x15, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x4e, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x38, 0x2e, 0x69, 0x6f, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x50, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x44, 0x65, 0x74,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65,
	0x73, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x83, 0x01, 0x0a, 0x12, 0x50, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x23,
	0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f,
	0x73, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x78, 0x70,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x53, 0x69, 0x6e, 0x63, 0x65, 0x22, 0xba, 0x01, 0x0a, 0x15, 0x50,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x74, 0x74, 0x72, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x74, 0x74, 0x72, 0x4b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x2a, 0x65, 0x0a, 0x0d, 0x46, 0x61, 0x69, 0x6c, 0x75,
	0x72, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e,
	0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x70, 0x69, 0x43, 0x61, 0x6c, 0x6c, 0x46, 0x61, 0x69,
	0x6c, 0x65, 0x64, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e,
	0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x6e, 0x61,
	0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x10, 0x04, 0x42, 0x08,
	0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_dc_device_management_events_proto_rawDescOnce sync.Once
	file_proto_dc_device_management_events_proto_rawDescData = file_proto_dc_device_management_events_proto_rawDesc
)

func file_proto_dc_device_management_events_proto_rawDescGZIP() []byte {
	file_proto_dc_device_management_events_proto_rawDescOnce.Do(func() {
		file_proto_dc_device_management_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dc_device_management_events_proto_rawDescData)
	})
	return file_proto_dc_device_management_events_proto_rawDescData
}

var file_proto_dc_device_management_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dc_device_management_events_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_dc_device_management_events_proto_goTypes = []interface{}{
	(FailureReason)(0),                      // 0: io.devicechain.devicemanagement.FailureReason
	(*PFailedEvent)(nil),                    // 1: io.devicechain.devicemanagement.PFailedEvent
	(*PResolvedAnchor)(nil),                 // 2: io.devicechain.devicemanagement.PResolvedAnchor
	(*PScopeMembership)(nil),                // 3: io.devicechain.devicemanagement.PScopeMembership
	(*PResolvedEvent)(nil),                  // 4: io.devicechain.devicemanagement.PResolvedEvent
	(*PResolvedNewRelationshipPayload)(nil), // 5: io.devicechain.devicemanagement.PResolvedNewRelationshipPayload
	(*PResolvedLocationEntry)(nil),          // 6: io.devicechain.devicemanagement.PResolvedLocationEntry
	(*PResolvedLocationsPayload)(nil),       // 7: io.devicechain.devicemanagement.PResolvedLocationsPayload
	(*PResolvedMeasurementEntry)(nil),       // 8: io.devicechain.devicemanagement.PResolvedMeasurementEntry
	(*PResolvedMeasurementsEntry)(nil),      // 9: io.devicechain.devicemanagement.PResolvedMeasurementsEntry
	(*PResolvedMeasurementsPayload)(nil),    // 10: io.devicechain.devicemanagement.PResolvedMeasurementsPayload
	(*PResolvedAlertEntry)(nil),             // 11: io.devicechain.devicemanagement.PResolvedAlertEntry
	(*PResolvedAlertsPayload)(nil),          // 12: io.devicechain.devicemanagement.PResolvedAlertsPayload
	(*PAlarmStateChangeEvent)(nil),          // 13: io.devicechain.devicemanagement.PAlarmStateChangeEvent
	(*PEntityDeletedEvent)(nil),             // 14: io.devicechain.devicemanagement.PEntityDeletedEvent
	(*PPublishedDetectionRule)(nil),         // 15: io.devicechain.devicemanagement.PPublishedDetectionRule
	(*PDetectionRulesPublishedEvent)(nil),   // 16: io.devicechain.devicemanagement.PDetectionRulesPublishedEvent
	(*PDeviceRosterEvent)(nil),              // 17: io.devicechain.devicemanagement.PDeviceRosterEvent
	(*PDeviceAttributeEvent)(nil),           // 18: io.devicechain.devicemanagement.PDeviceAttributeEvent
}
var file_proto_dc_device_management_events_proto_depIdxs = []int32{
	0,  // 0: io.devicechain.devicemanagement.PFailedEvent.reason:type_name -> io.devicechain.devicemanagement.FailureReason
	2,  // 1: io.devicechain.devicemanagement.PResolvedEvent.anchors:type_name -> io.devicechain.devicemanagement.PResolvedAnchor
	3,  // 2: io.devicechain.devicemanagement.PResolvedEvent.scope_memberships:type_name -> io.devicechain.devicemanagement.PScopeMembership
	6,  // 3: io.devicechain.devicemanagement.PResolvedLocationsPayload.entries:type_name -> io.devicechain.devicemanagement.PResolvedLocationEntry
	8,  // 4: io.devicechain.devicemanagement.PResolvedMeasurementsEntry.measurements:type_name -> io.devicechain.devicemanagement.PResolvedMeasurementEntry
	9,  // 5: io.devicechain.devicemanagement.PResolvedMeasurementsPayload.entries:type_name -> io.devicechain.devicemanagement.PResolvedMeasurementsEntry
	11, // 6: io.devicechain.devicemanagement.PResolvedAlertsPayload.entries:type_name -> io.devicechain.devicemanagement.PResolvedAlertEntry
	15, // 7: io.devicechain.devicemanagement.PDetectionRulesPublishedEvent.rules:type_name -> io.devicechain.devicemanagement.PPublishedDetectionRule
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_dc_device_management_events_proto_init() }
func file_proto_dc_device_management_events_proto_init() {
	if File_proto_dc_device_management_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dc_device_management_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PFailedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedAnchor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PScopeMembership); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedNewRelationshipPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedLocationEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedLocationsPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedMeasurementEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedMeasurementsEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedMeasurementsPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedAlertEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedAlertsPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PAlarmStateChangeEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PEntityDeletedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PPublishedDetectionRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PDetectionRulesPublishedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PDeviceRosterEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PDeviceAttributeEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_dc_device_management_events_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_proto_dc_device_management_events_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_proto_dc_device_management_events_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_proto_dc_device_management_events_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_proto_dc_device_management_events_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_proto_dc_device_management_events_proto_msgTypes[10].OneofWrappers = []interface{}{}
	file_proto_dc_device_management_events_proto_msgTypes[12].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dc_device_management_events_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dc_device_management_events_proto_goTypes,
		DependencyIndexes: file_proto_dc_device_management_events_proto_depIdxs,
		EnumInfos:         file_proto_dc_device_management_events_proto_enumTypes,
		MessageInfos:      file_proto_dc_device_management_events_proto_msgTypes,
	}.Build()
	File_proto_dc_device_management_events_proto = out.File
	file_proto_dc_device_management_events_proto_rawDesc = nil
	file_proto_dc_device_management_events_proto_goTypes = nil
	file_proto_dc_device_management_events_proto_depIdxs = nil
}
