// Copyright The DeviceChain Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: proto/dc-device-management-events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Enumeration of failure reasons.
type FailureReason int32

const (
	FailureReason_Unknown         FailureReason = 0 // Failed for unknown reason
	FailureReason_Invalid         FailureReason = 1 // Event was not able to be parsed
	FailureReason_ApiCallFailed   FailureReason = 2 // API call required for resolution failed
	FailureReason_DeviceNotFound  FailureReason = 3 // Device token could not be resolved to a device
	FailureReason_Unauthenticated FailureReason = 4 // Presented device credential was missing or invalid (ADR-014)
)

// Enum value maps for FailureReason.
var (
	FailureReason_name = map[int32]string{
		0: "Unknown",
		1: "Invalid",
		2: "ApiCallFailed",
		3: "DeviceNotFound",
		4: "Unauthenticated",
	}
	FailureReason_value = map[string]int32{
		"Unknown":         0,
		"Invalid":         1,
		"ApiCallFailed":   2,
		"DeviceNotFound":  3,
		"Unauthenticated": 4,
	}
)

func (x FailureReason) Enum() *FailureReason {
	p := new(FailureReason)
	*p = x
	return p
}

func (x FailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dc_device_management_events_proto_enumTypes[0].Descriptor()
}

func (FailureReason) Type() protoreflect.EnumType {
	return &file_proto_dc_device_management_events_proto_enumTypes[0]
}

func (x FailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureReason.Descriptor instead.
func (FailureReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{0}
}

// *
// Event that could not be processed.
type PFailedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason  FailureReason `protobuf:"varint,1,opt,name=reason,proto3,enum=io.devicechain.devicemanagement.FailureReason" json:"reason,omitempty"`
	Service string        `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Message string        `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error   string        `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Payload []byte        `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *PFailedEvent) Reset() {
	*x = PFailedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PFailedEvent) ProtoMessage() {}

func (x *PFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PFailedEvent.ProtoReflect.Descriptor instead.
func (*PFailedEvent) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{0}
}

func (x *PFailedEvent) GetReason() FailureReason {
	if x != nil {
		return x.Reason
	}
	return FailureReason_Unknown
}

func (x *PFailedEvent) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *PFailedEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PFailedEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PFailedEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// *
// A single resolved anchor: one of the device's tracked relationships at event
// time, denormalized so the event is queryable by that (type, id) dimension
// (ADR-013). A device with several tracked relationships yields several anchors.
type PResolvedAnchor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnchorType     string `protobuf:"bytes,1,opt,name=anchor_type,json=anchorType,proto3" json:"anchor_type,omitempty"`
	AnchorId       uint64 `protobuf:"varint,2,opt,name=anchor_id,json=anchorId,proto3" json:"anchor_id,omitempty"`
	RelationshipId uint64 `protobuf:"varint,3,opt,name=relationship_id,json=relationshipId,proto3" json:"relationship_id,omitempty"`
}

func (x *PResolvedAnchor) Reset() {
	*x = PResolvedAnchor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedAnchor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedAnchor) ProtoMessage() {}

func (x *PResolvedAnchor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedAnchor.ProtoReflect.Descriptor instead.
func (*PResolvedAnchor) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{1}
}

func (x *PResolvedAnchor) GetAnchorType() string {
	if x != nil {
		return x.AnchorType
	}
	return ""
}

func (x *PResolvedAnchor) GetAnchorId() uint64 {
	if x != nil {
		return x.AnchorId
	}
	return 0
}

func (x *PResolvedAnchor) GetRelationshipId() uint64 {
	if x != nil {
		return x.RelationshipId
	}
	return 0
}

// *
// Event that was successfully resolved. It carries the full set of the device's
// tracked-relationship anchors (empty when the device is unassigned).
type PResolvedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source         string             `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	AltId          *string            `protobuf:"bytes,2,opt,name=alt_id,json=altId,proto3,oneof" json:"alt_id,omitempty"`
	SourceDeviceId uint64             `protobuf:"varint,3,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	Anchors        []*PResolvedAnchor `protobuf:"bytes,4,rep,name=anchors,proto3" json:"anchors,omitempty"`
	OccurredTime   string             `protobuf:"bytes,7,opt,name=occurred_time,json=occurredTime,proto3" json:"occurred_time,omitempty"`
	ProcessedTime  string             `protobuf:"bytes,8,opt,name=processed_time,json=processedTime,proto3" json:"processed_time,omitempty"`
	EventType      int64              `protobuf:"varint,9,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload        []byte             `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *PResolvedEvent) Reset() {
	*x = PResolvedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedEvent) ProtoMessage() {}

func (x *PResolvedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedEvent.ProtoReflect.Descriptor instead.
func (*PResolvedEvent) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{2}
}

func (x *PResolvedEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PResolvedEvent) GetAltId() string {
	if x != nil && x.AltId != nil {
		return *x.AltId
	}
	return ""
}

func (x *PResolvedEvent) GetSourceDeviceId() uint64 {
	if x != nil {
		return x.SourceDeviceId
	}
	return 0
}

func (x *PResolvedEvent) GetAnchors() []*PResolvedAnchor {
	if x != nil {
		return x.Anchors
	}
	return nil
}

func (x *PResolvedEvent) GetOccurredTime() string {
	if x != nil {
		return x.OccurredTime
	}
	return ""
}

func (x *PResolvedEvent) GetProcessedTime() string {
	if x != nil {
		return x.ProcessedTime
	}
	return ""
}

func (x *PResolvedEvent) GetEventType() int64 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *PResolvedEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// *
// Payload for resolved new relationship request. The target is a uniform
// (type, id) reference (ADR-013).
type PResolvedNewRelationshipPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RelationshipTypeId uint64  `protobuf:"varint,1,opt,name=relationship_type_id,json=relationshipTypeId,proto3" json:"relationship_type_id,omitempty"`
	TargetType         *string `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3,oneof" json:"target_type,omitempty"`
	TargetId           *uint64 `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3,oneof" json:"target_id,omitempty"`
}

func (x *PResolvedNewRelationshipPayload) Reset() {
	*x = PResolvedNewRelationshipPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedNewRelationshipPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedNewRelationshipPayload) ProtoMessage() {}

func (x *PResolvedNewRelationshipPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedNewRelationshipPayload.ProtoReflect.Descriptor instead.
func (*PResolvedNewRelationshipPayload) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{3}
}

func (x *PResolvedNewRelationshipPayload) GetRelationshipTypeId() uint64 {
	if x != nil {
		return x.RelationshipTypeId
	}
	return 0
}

func (x *PResolvedNewRelationshipPayload) GetTargetType() string {
	if x != nil && x.TargetType != nil {
		return *x.TargetType
	}
	return ""
}

func (x *PResolvedNewRelationshipPayload) GetTargetId() uint64 {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return 0
}

// *
// Single location entry for a location payload.
type PResolvedLocationEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude     *string `protobuf:"bytes,1,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude    *string `protobuf:"bytes,2,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	Elevation    *string `protobuf:"bytes,3,opt,name=elevation,proto3,oneof" json:"elevation,omitempty"`
	OccurredTime *string `protobuf:"bytes,4,opt,name=occurred_time,json=occurredTime,proto3,oneof" json:"occurred_time,omitempty"`
}

func (x *PResolvedLocationEntry) Reset() {
	*x = PResolvedLocationEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedLocationEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedLocationEntry) ProtoMessage() {}

func (x *PResolvedLocationEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedLocationEntry.ProtoReflect.Descriptor instead.
func (*PResolvedLocationEntry) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{4}
}

func (x *PResolvedLocationEntry) GetLatitude() string {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return ""
}

func (x *PResolvedLocationEntry) GetLongitude() string {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return ""
}

func (x *PResolvedLocationEntry) GetElevation() string {
	if x != nil && x.Elevation != nil {
		return *x.Elevation
	}
	return ""
}

func (x *PResolvedLocationEntry) GetOccurredTime() string {
	if x != nil && x.OccurredTime != nil {
		return *x.OccurredTime
	}
	return ""
}

// *
// Payload for a location event.
type PResolvedLocationsPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*PResolvedLocationEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *PResolvedLocationsPayload) Reset() {
	*x = PResolvedLocationsPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedLocationsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedLocationsPayload) ProtoMessage() {}

func (x *PResolvedLocationsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedLocationsPayload.ProtoReflect.Descriptor instead.
func (*PResolvedLocationsPayload) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{5}
}

func (x *PResolvedLocationsPayload) GetEntries() []*PResolvedLocationEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// *
// Single measurement entry for a measurement payload.
type PResolvedMeasurementEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value      string  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Classifier *uint64 `protobuf:"varint,3,opt,name=classifier,proto3,oneof" json:"classifier,omitempty"`
}

func (x *PResolvedMeasurementEntry) Reset() {
	*x = PResolvedMeasurementEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedMeasurementEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedMeasurementEntry) ProtoMessage() {}

func (x *PResolvedMeasurementEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedMeasurementEntry.ProtoReflect.Descriptor instead.
func (*PResolvedMeasurementEntry) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{6}
}

func (x *PResolvedMeasurementEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PResolvedMeasurementEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PResolvedMeasurementEntry) GetClassifier() uint64 {
	if x != nil && x.Classifier != nil {
		return *x.Classifier
	}
	return 0
}

// *
// Single measurement entry for a measurement payload.
type PResolvedMeasurementsEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Measurements []*PResolvedMeasurementEntry `protobuf:"bytes,1,rep,name=measurements,proto3" json:"measurements,omitempty"`
	OccurredTime *string                      `protobuf:"bytes,2,opt,name=occurred_time,json=occurredTime,proto3,oneof" json:"occurred_time,omitempty"`
}

func (x *PResolvedMeasurementsEntry) Reset() {
	*x = PResolvedMeasurementsEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedMeasurementsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedMeasurementsEntry) ProtoMessage() {}

func (x *PResolvedMeasurementsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedMeasurementsEntry.ProtoReflect.Descriptor instead.
func (*PResolvedMeasurementsEntry) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{7}
}

func (x *PResolvedMeasurementsEntry) GetMeasurements() []*PResolvedMeasurementEntry {
	if x != nil {
		return x.Measurements
	}
	return nil
}

func (x *PResolvedMeasurementsEntry) GetOccurredTime() string {
	if x != nil && x.OccurredTime != nil {
		return *x.OccurredTime
	}
	return ""
}

// *
// Payload for a measurement event.
type PResolvedMeasurementsPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*PResolvedMeasurementsEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *PResolvedMeasurementsPayload) Reset() {
	*x = PResolvedMeasurementsPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedMeasurementsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedMeasurementsPayload) ProtoMessage() {}

func (x *PResolvedMeasurementsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedMeasurementsPayload.ProtoReflect.Descriptor instead.
func (*PResolvedMeasurementsPayload) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{8}
}

func (x *PResolvedMeasurementsPayload) GetEntries() []*PResolvedMeasurementsEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// *
// Single alert entry for an alerts payload.
type PResolvedAlertEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         string  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Level        uint32  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Message      string  `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Source       string  `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	OccurredTime *string `protobuf:"bytes,5,opt,name=occurred_time,json=occurredTime,proto3,oneof" json:"occurred_time,omitempty"`
}

func (x *PResolvedAlertEntry) Reset() {
	*x = PResolvedAlertEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedAlertEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedAlertEntry) ProtoMessage() {}

func (x *PResolvedAlertEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedAlertEntry.ProtoReflect.Descriptor instead.
func (*PResolvedAlertEntry) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{9}
}

func (x *PResolvedAlertEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PResolvedAlertEntry) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PResolvedAlertEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PResolvedAlertEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PResolvedAlertEntry) GetOccurredTime() string {
	if x != nil && x.OccurredTime != nil {
		return *x.OccurredTime
	}
	return ""
}

// *
// Payload for an alert event.
type PResolvedAlertsPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*PResolvedAlertEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *PResolvedAlertsPayload) Reset() {
	*x = PResolvedAlertsPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PResolvedAlertsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PResolvedAlertsPayload) ProtoMessage() {}

func (x *PResolvedAlertsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PResolvedAlertsPayload.ProtoReflect.Descriptor instead.
func (*PResolvedAlertsPayload) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{10}
}

func (x *PResolvedAlertsPayload) GetEntries() []*PResolvedAlertEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// *
// Alarm state-change event (ADR-041): re-emitted whenever a raised alarm
// transitions (raised/escalated/de-escalated/cleared/acknowledged). It is a
// snapshot of the alarm after the transition plus the transition kind and the
// prior severity (for a severity change), and is the substrate for graphql-ws
// subscriptions (ADR-037) and notifications (ADR-017).
type PAlarmStateChangeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType        string   `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	AlarmToken       string   `protobuf:"bytes,2,opt,name=alarm_token,json=alarmToken,proto3" json:"alarm_token,omitempty"`
	OriginatorType   string   `protobuf:"bytes,3,opt,name=originator_type,json=originatorType,proto3" json:"originator_type,omitempty"`
	OriginatorId     uint64   `protobuf:"varint,4,opt,name=originator_id,json=originatorId,proto3" json:"originator_id,omitempty"`
	AlarmKey         string   `protobuf:"bytes,5,opt,name=alarm_key,json=alarmKey,proto3" json:"alarm_key,omitempty"`
	MetricKey        string   `protobuf:"bytes,6,opt,name=metric_key,json=metricKey,proto3" json:"metric_key,omitempty"`
	State            string   `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	Severity         string   `protobuf:"bytes,8,opt,name=severity,proto3" json:"severity,omitempty"`
	Acknowledged     bool     `protobuf:"varint,9,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	PreviousSeverity *string  `protobuf:"bytes,10,opt,name=previous_severity,json=previousSeverity,proto3,oneof" json:"previous_severity,omitempty"`
	AcknowledgedBy   *string  `protobuf:"bytes,11,opt,name=acknowledged_by,json=acknowledgedBy,proto3,oneof" json:"acknowledged_by,omitempty"`
	LastValue        *float64 `protobuf:"fixed64,12,opt,name=last_value,json=lastValue,proto3,oneof" json:"last_value,omitempty"`
	Message          *string  `protobuf:"bytes,13,opt,name=message,proto3,oneof" json:"message,omitempty"`
	OccurredTime     string   `protobuf:"bytes,14,opt,name=occurred_time,json=occurredTime,proto3" json:"occurred_time,omitempty"`
}

func (x *PAlarmStateChangeEvent) Reset() {
	*x = PAlarmStateChangeEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dc_device_management_events_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PAlarmStateChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PAlarmStateChangeEvent) ProtoMessage() {}

func (x *PAlarmStateChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dc_device_management_events_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PAlarmStateChangeEvent.ProtoReflect.Descriptor instead.
func (*PAlarmStateChangeEvent) Descriptor() ([]byte, []int) {
	return file_proto_dc_device_management_events_proto_rawDescGZIP(), []int{11}
}

func (x *PAlarmStateChangeEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetAlarmToken() string {
	if x != nil {
		return x.AlarmToken
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetOriginatorType() string {
	if x != nil {
		return x.OriginatorType
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetOriginatorId() uint64 {
	if x != nil {
		return x.OriginatorId
	}
	return 0
}

func (x *PAlarmStateChangeEvent) GetAlarmKey() string {
	if x != nil {
		return x.AlarmKey
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetMetricKey() string {
	if x != nil {
		return x.MetricKey
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *PAlarmStateChangeEvent) GetPreviousSeverity() string {
	if x != nil && x.PreviousSeverity != nil {
		return *x.PreviousSeverity
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetAcknowledgedBy() string {
	if x != nil && x.AcknowledgedBy != nil {
		return *x.AcknowledgedBy
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetLastValue() float64 {
	if x != nil && x.LastValue != nil {
		return *x.LastValue
	}
	return 0
}

func (x *PAlarmStateChangeEvent) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *PAlarmStateChangeEvent) GetOccurredTime() string {
	if x != nil {
		return x.OccurredTime
	}
	return ""
}

var File_proto_dc_device_management_events_proto protoreflect.FileDescriptor

var file_proto_dc_device_management_events_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x63, 0x2d, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x69, 0x6f, 0x2e, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xba, 0x01, 0x0a, 0x0c, 0x50,
	0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x46, 0x0a, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e, 0x2e, 0x69, 0x6f,
	0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x46, 0x61,
	0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x78, 0x0a, 0x0f, 0x50, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x64, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6e,
	0x63, 0x68, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61,
	0x6e, 0x63, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x49,
	0x64, 0x22, 0xca, 0x02, 0x0a, 0x0e, 0x50, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x06,
	0x61, 0x6c, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05,
	0x61, 0x6c, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x4a, 0x0a, 0x07, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x69, 0x6f, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x41,
	0x6e, 0x63, 0x68, 0x6f, 0x72, 0x52, 0x07, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x73, 0x12, 0x23,
	0x0a, 0x0d, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x61, 0x6c, 0x74, 0x5f, 0x69, 0x64, 0x22, 0xb9,
	0x01, 0x0a, 0x1f, 0x50, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x4e, 0x65, 0x77, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x30, 0x0a, 0x14, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68,
	0x69, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x12, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x54, 0x79,
	0x70, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x48, 0x01, 0x52,
	0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c,
	0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x0c, 0x0a, 0x0a,
	0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x22, 0xe4, 0x01, 0x0a, 0x16, 0x50,
	0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e,
	0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x65, 0x6c, 0x65,
	0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x09,
	0x65, 0x6c, 0x65, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x28, 0x0a, 0x0d,
	0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x0c, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x65, 0x6c, 0x65, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x10, 0x0a, 0x0e, 0x5f, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x22, 0x6e, 0x0a, 0x19, 0x50, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x51,
	0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x37, 0x2e, 0x69, 0x6f, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x50, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x22, 0x79, 0x0a, 0x19, 0x50, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x4d, 0x65,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x0a,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a,
	0x0b, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0xb8, 0x01, 0x0a,
	0x1a, 0x50, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x5e, 0x0a, 0x0c, 0x6d,
	0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x3a, 0x2e, 0x69, 0x6f, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x50, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x4d, 0x65, 0x61,
	0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x6d,
	0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x28, 0x0a, 0x0d, 0x6f,
	0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x75, 0x0a, 0x1c, 0x50, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x64, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x55, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x69, 0x6f, 0x2e, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x64, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0xad,
	0x01, 0x0a, 0x13, 0x50, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x41, 0x6c, 0x65, 0x72,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x28, 0x0a, 0x0d, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x6f, 0x63, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x10, 0x0a, 0x0e,
	0x5f, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x68,
	0x0a, 0x16, 0x50, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x41, 0x6c, 0x65, 0x72, 0x74,
	0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x4e, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x69, 0x6f, 0x2e, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x52, 0x65, 0x73,
	0x6f, 0x6c, 0x76, 0x65, 0x64, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0xc5, 0x04, 0x0a, 0x16, 0x50, 0x41, 0x6c,
	0x61, 0x72, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x5f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f,
	0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x4b, 0x65, 0x79, 0x12, 0x1d,
	0x0a, 0x0a, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x12,
	0x22, 0x0a, 0x0c, 0x61, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x64, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x64, 0x12, 0x30, 0x0a, 0x11, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x5f,
	0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x10, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69,
	0x74, 0x79, 0x88, 0x01, 0x01, 0x12, 0x2c, 0x0a, 0x0f, 0x61, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x0e, 0x61, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x64, 0x42, 0x79,
	0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x48, 0x02, 0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f,
	0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x14, 0x0a, 0x12, 0x5f,
	0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x5f, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74,
	0x79, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x61, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x64, 0x5f, 0x62, 0x79, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2a, 0x65, 0x0a, 0x0d, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x41,
	0x70, 0x69, 0x43, 0x61, 0x6c, 0x6c, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x02, 0x12, 0x12,
	0x0a, 0x0e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64,
	0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x6e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x64, 0x10, 0x04, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_dc_device_management_events_proto_rawDescOnce sync.Once
	file_proto_dc_device_management_events_proto_rawDescData = file_proto_dc_device_management_events_proto_rawDesc
)

func file_proto_dc_device_management_events_proto_rawDescGZIP() []byte {
	file_proto_dc_device_management_events_proto_rawDescOnce.Do(func() {
		file_proto_dc_device_management_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dc_device_management_events_proto_rawDescData)
	})
	return file_proto_dc_device_management_events_proto_rawDescData
}

var file_proto_dc_device_management_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dc_device_management_events_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_dc_device_management_events_proto_goTypes = []interface{}{
	(FailureReason)(0),                      // 0: io.devicechain.devicemanagement.FailureReason
	(*PFailedEvent)(nil),                    // 1: io.devicechain.devicemanagement.PFailedEvent
	(*PResolvedAnchor)(nil),                 // 2: io.devicechain.devicemanagement.PResolvedAnchor
	(*PResolvedEvent)(nil),                  // 3: io.devicechain.devicemanagement.PResolvedEvent
	(*PResolvedNewRelationshipPayload)(nil), // 4: io.devicechain.devicemanagement.PResolvedNewRelationshipPayload
	(*PResolvedLocationEntry)(nil),          // 5: io.devicechain.devicemanagement.PResolvedLocationEntry
	(*PResolvedLocationsPayload)(nil),       // 6: io.devicechain.devicemanagement.PResolvedLocationsPayload
	(*PResolvedMeasurementEntry)(nil),       // 7: io.devicechain.devicemanagement.PResolvedMeasurementEntry
	(*PResolvedMeasurementsEntry)(nil),      // 8: io.devicechain.devicemanagement.PResolvedMeasurementsEntry
	(*PResolvedMeasurementsPayload)(nil),    // 9: io.devicechain.devicemanagement.PResolvedMeasurementsPayload
	(*PResolvedAlertEntry)(nil),             // 10: io.devicechain.devicemanagement.PResolvedAlertEntry
	(*PResolvedAlertsPayload)(nil),          // 11: io.devicechain.devicemanagement.PResolvedAlertsPayload
	(*PAlarmStateChangeEvent)(nil),          // 12: io.devicechain.devicemanagement.PAlarmStateChangeEvent
}
var file_proto_dc_device_management_events_proto_depIdxs = []int32{
	0,  // 0: io.devicechain.devicemanagement.PFailedEvent.reason:type_name -> io.devicechain.devicemanagement.FailureReason
	2,  // 1: io.devicechain.devicemanagement.PResolvedEvent.anchors:type_name -> io.devicechain.devicemanagement.PResolvedAnchor
	5,  // 2: io.devicechain.devicemanagement.PResolvedLocationsPayload.entries:type_name -> io.devicechain.devicemanagement.PResolvedLocationEntry
	7,  // 3: io.devicechain.devicemanagement.PResolvedMeasurementsEntry.measurements:type_name -> io.devicechain.devicemanagement.PResolvedMeasurementEntry
	8,  // 4: io.devicechain.devicemanagement.PResolvedMeasurementsPayload.entries:type_name -> io.devicechain.devicemanagement.PResolvedMeasurementsEntry
	10, // 5: io.devicechain.devicemanagement.PResolvedAlertsPayload.entries:type_name -> io.devicechain.devicemanagement.PResolvedAlertEntry
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_dc_device_management_events_proto_init() }
func file_proto_dc_device_management_events_proto_init() {
	if File_proto_dc_device_management_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dc_device_management_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PFailedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedAnchor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedNewRelationshipPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedLocationEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedLocationsPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedMeasurementEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedMeasurementsEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedMeasurementsPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedAlertEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PResolvedAlertsPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dc_device_management_events_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PAlarmStateChangeEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_dc_device_management_events_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_proto_dc_device_management_events_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_proto_dc_device_management_events_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_proto_dc_device_management_events_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_proto_dc_device_management_events_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_proto_dc_device_management_events_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_proto_dc_device_management_events_proto_msgTypes[11].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dc_device_management_events_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dc_device_management_events_proto_goTypes,
		DependencyIndexes: file_proto_dc_device_management_events_proto_depIdxs,
		EnumInfos:         file_proto_dc_device_management_events_proto_enumTypes,
		MessageInfos:      file_proto_dc_device_management_events_proto_msgTypes,
	}.Build()
	File_proto_dc_device_management_events_proto = out.File
	file_proto_dc_device_management_events_proto_rawDesc = nil
	file_proto_dc_device_management_events_proto_goTypes = nil
	file_proto_dc_device_management_events_proto_depIdxs = nil
}
