// Copyright The DeviceChain Authors
// SPDX-License-Identifier: Apache-2.0

package model

import (
	"bytes"
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// The alarm WIRE vocabulary the sim scenarios mirror, held to the enums that own it.
//
// dc-simulator cannot import this module — it is deliberately an untrusted external
// client of the platform — so every alarm value it speaks is a hand-copied literal:
// "MAJOR" for the tier a raise lands at, "ACTIVE"/"CLEARED" for the durable row's
// state. Those literals are read back in comparisons whose FALSE branch is the passing
// one. A load-test oracle asserting a safety probe never went ACTIVE compares against
// its own copy of the string; rename the state here and the comparison stops being able
// to match, so the oracle reports no spurious alarm and PASSES — about a check that can
// no longer fail. That is strictly worse than a broken test.
//
// Until this file existed the only gate over any of it was inside the sim, comparing the
// sim's two copies to EACH OTHER (wire == ToUpper(authoring)) — self-consistent by
// construction, and blind to both real enums.
//
// The fixture is generated by the sim from the same values its provisioning paths
// publish and its oracles query (backend/sims/dc-simulator/loadtest/
// authored_rules_fixture_test.go, which also carries the staleness gate).

const authoredRuleFixturePath = "../../../testdata/authored-rules/authored-rules.json"

type authoredRuleFixture struct {
	Rules []authoredSimRule `json:"rules"`
	// WireVocabulary carries every enum the sim mirrors, grouped by owning module. Only
	// alarmState is this module's to judge; the other groups are declared so the
	// fail-closed decode below does not reject the file, and are deliberately left
	// unjudged here — command-delivery and event-processing hold their own.
	WireVocabulary struct {
		AlarmState struct {
			Active  string `json:"active"`
			Cleared string `json:"cleared"`
		} `json:"alarmState"`
		CommandStatus       json.RawMessage `json:"commandStatus"`
		DetectionRuleStatus json.RawMessage `json:"detectionRuleStatus"`
	} `json:"wireVocabulary"`
}

// authoredSimRule mirrors one fixture entry. Decoded with DisallowUnknownFields, so a
// field added on the producing side fails here loudly rather than being dropped.
type authoredSimRule struct {
	Producer          string `json:"producer"`
	RuleToken         string `json:"ruleToken"`
	ProfileToken      string `json:"profileToken"`
	Enabled           bool   `json:"enabled"`
	AlarmSeverityWire string `json:"alarmSeverityWire"`
	Definition        string `json:"definition"`
	GroupScoped       bool   `json:"groupScoped"`
}

// publishedRule is the slice of the opaque rule definition this module cares about: the
// authoring severity a raise carries, and whether the rule raises an alarm at all. It
// decodes leniently on purpose — the rule GRAMMAR is event-processing's authority and is
// gated there against the real publish gate, so re-asserting it here would be a second,
// weaker copy of that check that has to agree with the first one.
type publishedRule struct {
	Severity string `json:"severity"`
	Actions  []struct {
		Type string `json:"type"`
	} `json:"actions"`
}

func (r publishedRule) raisesAlarm() bool {
	for _, a := range r.Actions {
		if a.Type == "raiseAlarm" {
			return true
		}
	}
	return false
}

func loadAuthoredSimFixture(t *testing.T) authoredRuleFixture {
	t.Helper()
	raw, err := os.ReadFile(authoredRuleFixturePath)
	if err != nil {
		t.Fatalf("read %s: %v\n\nThis fixture is the ONLY thing tying the sim's mirrored alarm "+
			"wire values to this module's enums. If it moved, re-point this test rather than "+
			"deleting it; regenerate it with:\n  cd backend/sims/dc-simulator && go test "+
			"./loadtest/ -run TestAuthoredRuleFixtureIsCurrent -update-rule-fixture",
			authoredRuleFixturePath, err)
	}
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	var fixture authoredRuleFixture
	if err := dec.Decode(&fixture); err != nil {
		t.Fatalf("decode %s: %v (a field added on the producing side must be mirrored here, "+
			"not ignored)", authoredRuleFixturePath, err)
	}
	if len(fixture.Rules) == 0 {
		t.Fatal("the fixture declares no rules, so every check here is vacuous")
	}
	return fixture
}

// TestAuthoredSimAlarmSeverityIsARealTier holds each scenario's mirrored severity to the
// real AlarmSeverity enum, via the real conversion, applied to the real published rule.
func TestAuthoredSimAlarmSeverityIsARealTier(t *testing.T) {
	checked := 0
	for _, entry := range loadAuthoredSimFixture(t).Rules {
		var rule publishedRule
		if err := json.Unmarshal([]byte(entry.Definition), &rule); err != nil {
			t.Errorf("%s/%s: rule definition is not decodable: %v", entry.Producer, entry.RuleToken, err)
			continue
		}
		if !rule.raisesAlarm() {
			// A rule with no raiseAlarm action legitimately carries no tier, and its
			// mirrored wire severity would be describing an alarm that is never raised.
			continue
		}
		checked++

		// 1. The mirrored literal must be what the REAL conversion produces from the REAL
		//    published severity.
		//
		//    This is the check the sim could not make. Its own gate compared its two
		//    constants to each other (wire == ToUpper(authoring)) — which does catch a
		//    ONE-SIDED edit, but is satisfied by the mistake that actually shipped: a
		//    scenario that collapsed BOTH to "MAJOR" passes a ToUpper identity, while
		//    "MAJOR" is not a severity the rule compiler accepts at all. Comparing against
		//    the published definition through this module's real conversion is what makes
		//    the collapse visible.
		want := AlarmSeverityFromRuleSeverity(rule.Severity)
		if AlarmSeverity(entry.AlarmSeverityWire) != want {
			t.Errorf("%s/%s mirrors alarm severity %q, but its published rule authors %q, "+
				"which lands on the durable row as %q — an alarm widget or oracle filtering "+
				"on the mirrored value matches nothing and renders as 'no alarms yet'",
				entry.Producer, entry.RuleToken, entry.AlarmSeverityWire, rule.Severity, want)
		}

		// 2. And that tier must actually exist. A rule authoring a severity this module
		//    does not know is dropped by the raise-alarm consumer as malformed — the
		//    detection fires, the alarm never appears, and only a log line says so.
		if !want.Valid() {
			t.Errorf("%s/%s authors severity %q, which maps to %q — not a known AlarmSeverity, "+
				"so the raise-alarm consumer drops every raise this rule produces as malformed",
				entry.Producer, entry.RuleToken, rule.Severity, want)
		}
	}
	if checked == 0 {
		t.Fatal("no authored rule raises an alarm, so this test asserted nothing — the sim's " +
			"alarm severities are unchecked and the widgets that depend on them unproven")
	}
}

// 🔴 The check above is worth something only because the two vocabularies genuinely
// differ in case. If AlarmSeverity ever accepted the lowercase authoring form too, the
// conversion would stop being load-bearing, a scenario that collapsed its two constants
// into one would be accepted — and it would then be REJECTED by event-processing's
// compiler, which does not accept the uppercase form. The failure would land on the far
// side of the boundary from the mistake.
//
// This is not hypothetical: widgetlab shipped "MAJOR" as its authoring severity once,
// having collapsed the pair the load-test harness deliberately keeps apart.
func TestTheTwoAlarmVocabulariesReallyDoDiffer(t *testing.T) {
	// AllAlarmSeverities, not a hand-written list: a sixth tier added to the enum would
	// simply sit outside a literal list here, silently unchecked. Ranging over the one
	// declaration means a new tier is covered the moment it can be ranked at all.
	tiers := AllAlarmSeverities()
	if len(tiers) == 0 {
		t.Fatal("the severity vocabulary is empty, so this test asserted nothing")
	}
	for _, tier := range tiers {
		if !tier.Valid() {
			t.Fatalf("%q is declared but not accepted by Valid(), so this module's own "+
				"vocabulary is inconsistent", tier)
		}
		lower := AlarmSeverity(strings.ToLower(string(tier)))
		if lower == tier {
			t.Errorf("%q is case-identical to its authoring form, so the conversion carries "+
				"no information for this tier", tier)
			continue
		}
		if lower.Valid() {
			t.Errorf("AlarmSeverity now accepts the lowercase authoring form %q — the wire and "+
				"authoring vocabularies no longer differ, so nothing catches a scenario that "+
				"collapses them, and event-processing's compiler (which rejects the uppercase "+
				"form) becomes the only thing that does", lower)
		}
	}
}

// The durable alarm STATE the sim's oracles compare against. Same hazard, different
// vocabulary: these appear in queries whose non-matching result is the PASSING one.
func TestAuthoredSimAlarmStatesAreRealStates(t *testing.T) {
	wire := loadAuthoredSimFixture(t).WireVocabulary.AlarmState
	if wire.Active == "" || wire.Cleared == "" {
		t.Fatal("the fixture carries no alarm-state vocabulary, so this test asserted nothing")
	}
	if got := AlarmState(wire.Active); got != AlarmStateActive {
		t.Errorf("the sim compares against active state %q, but the durable row is written "+
			"%q — a spurious-alarm oracle would compare against a value that can never "+
			"match and PASS", wire.Active, AlarmStateActive)
	}
	if got := AlarmState(wire.Cleared); got != AlarmStateCleared {
		t.Errorf("the sim compares against cleared state %q, but the durable row is written "+
			"%q — a raised-and-cleared liveness check would never see its terminal state",
			wire.Cleared, AlarmStateCleared)
	}
	// Equality above already implies validity; asserted anyway so that dropping a state
	// from Valid() while keeping its declaration is caught here rather than at runtime.
	if !AlarmState(wire.Active).Valid() || !AlarmState(wire.Cleared).Valid() {
		t.Errorf("a mirrored alarm state is declared but no longer accepted by AlarmState.Valid()")
	}
}
