// Copyright The DeviceChain Authors
// SPDX-License-Identifier: Apache-2.0

// Command genauth mints a fresh set of NATS broker-auth credentials (ADR-025) and
// prints them as shell-assignable KEY=VALUE lines. It exists so the non-dcctl
// bring-up path (deploy/local/up.sh) can provision the same credentials dcctl
// mints in-process — nkeys can't be generated by the OpenTofu `tls`/`random`
// providers or in bash, so this Go helper is the shared minting entrypoint.
//
// Usage (from the repo root, resolved via go.work):
//
//	eval "$(go run ./backend/core/natsauth/cmd/genauth)"
//
// Emits:
//
//	NATS_CALLOUT_ISSUER_PUBLIC=A...   # server-config auth_callout.issuer (public)
//	NATS_CALLOUT_ISSUER_SEED=SA...    # the device-management responder signs with this
//	NATS_SERVICE_PASSWORD=...         # shared dc_service login password
//
// The values are the nkey/hex alphabet only, so eval-ing them is injection-safe.
package main

import (
	"fmt"
	"os"

	"github.com/devicechain-io/dc-microservice/natsauth"
)

func main() {
	c, err := natsauth.GenerateCredentials()
	if err != nil {
		fmt.Fprintln(os.Stderr, "genauth:", err)
		os.Exit(1)
	}
	fmt.Printf("NATS_CALLOUT_ISSUER_PUBLIC=%s\n", c.IssuerPublic)
	fmt.Printf("NATS_CALLOUT_ISSUER_SEED=%s\n", c.IssuerSeed)
	fmt.Printf("NATS_SERVICE_PASSWORD=%s\n", c.ServicePassword)
}
