import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// The sidebar is generated automatically from the folder structure and the
// `_category_.json` files in each directory. Add new docs by dropping a
// Markdown file into the appropriate folder under docs/.
const sidebars: SidebarsConfig = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
