import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// The sidebar is hand-written, not autogenerated, because Concepts is grouped
// into sub-categories that deliberately do NOT exist as folders on disk.
//
// Grouping here rather than in the file tree is the whole point: a page can be
// regrouped without moving its file. Moving it would change its URL (a doc's
// route follows its path), break every relative `./page.md` link that points at
// it, and have to be mirrored byte-for-byte in i18n/es — for a change that is
// purely about how the nav reads.
//
// Two consequences, both deliberate:
//
//   - `sidebar_position` front matter is IGNORED for any doc listed explicitly
//     below, so the concepts/ pages no longer carry it (its value would be a
//     lie). The categories that defer to `autogenerated` still honour it.
//
//   - `_category_.json` is read ONLY by the autogenerated generator, so a
//     folder's label and description have to live here instead. Their Spanish
//     strings live in i18n/es/docusaurus-plugin-content-docs/current.json under
//     `sidebar.docs.category.*`; after adding or renaming a category, run
//     `npm run write-translations` and translate the new keys, or the Spanish
//     sidebar silently falls back to the English label.
//
// Adding a doc under Concepts means adding it to a group below. Guides,
// Reference and Deployment still autogenerate from their folders, so a new file
// dropped in there appears on its own, ordered by `sidebar_position`.
//
// Category URLs are `/category/<slugified label>`, so renaming a label changes
// a live URL. Rename deliberately.

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Concepts',
      link: {
        type: 'generated-index',
        description:
          "How DeviceChain is designed — the foundations it is built on, how devices connect to it, how their events turn into automated action, how all of it is visualized, and the platform services behind a tenant.",
      },
      items: [
        {
          type: 'category',
          label: 'Foundations',
          collapsed: false,
          items: [
            'concepts/architecture',
            'concepts/domain-model',
            'concepts/multi-tenancy',
          ],
        },
        {
          type: 'category',
          label: 'Device Connectivity',
          collapsed: false,
          items: [
            'concepts/sparkplug',
            'concepts/lwm2m',
            'concepts/device-presence',
            // Directly after presence on purpose: whether a command is dispatched
            // or held is decided by whether the device is present, so the two read
            // as one story.
            'concepts/commands',
          ],
        },
        {
          type: 'category',
          label: 'Automation',
          collapsed: false,
          items: [
            'concepts/event-processing',
            'concepts/geofencing',
            'concepts/ai-authoring',
            'concepts/outbound-connectors',
          ],
        },
        {
          type: 'category',
          label: 'Visualization',
          collapsed: false,
          items: [
            'concepts/dashboards',
            'concepts/basemaps',
            'concepts/white-labeling',
          ],
        },
        {
          type: 'category',
          label: 'Platform Services',
          collapsed: false,
          items: [
            'concepts/governance',
            'concepts/tenant-tiers',
            'concepts/system-settings',
            'concepts/object-storage',
            'concepts/mcp',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        description:
          'Task-oriented how-to guides for running and using DeviceChain.',
      },
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {
        type: 'generated-index',
        description:
          'Reference material — the GraphQL API and configuration.',
      },
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
    {
      type: 'category',
      label: 'Deployment',
      link: {
        type: 'generated-index',
        description:
          'Operating DeviceChain — the Kubernetes operator and infrastructure provisioning.',
      },
      items: [{ type: 'autogenerated', dirName: 'deployment' }],
    },
    'getting-help',
  ],
};

export default sidebars;
