// Code generated by "stringer -type=LifecycleState"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Uninitialized-0]
	_ = x[Initializing-1]
	_ = x[Initialized-2]
	_ = x[Starting-3]
	_ = x[Started-4]
	_ = x[Stopping-5]
	_ = x[Stopped-6]
	_ = x[Terminating-7]
	_ = x[Terminated-8]
}

const _LifecycleState_name = "UninitializedInitializingInitializedStartingStartedStoppingStoppedTerminatingTerminated"

var _LifecycleState_index = [...]uint8{0, 13, 25, 36, 44, 51, 59, 66, 77, 87}

func (i LifecycleState) String() string {
	if i < 0 || i >= LifecycleState(len(_LifecycleState_index)-1) {
		return "LifecycleState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LifecycleState_name[_LifecycleState_index[i]:_LifecycleState_index[i+1]]
}
