// Copyright The DeviceChain Authors
// SPDX-License-Identifier: Apache-2.0

// Generate every consumer-facing representation of the brand from tokens.json.
//
//     node tools/generate.mjs          # write css/*
//     node tools/generate.mjs --check  # fail if anything on disk is stale
//
// Three outputs, because the three consumers do NOT share a vocabulary and a
// single stylesheet cannot serve them:
//
//   css/brand.css   marketing/static:  --brand, --ink, --bg, accents (hex)
//   css/shadcn.css  console:           --primary, --foreground, ... (BARE HSL
//                                      triples, which is what Tailwind needs)
//   css/infima.css  docs:              --ifm-color-primary* (hex, with the
//                                      light/dark ramp Infima expects)
//
// Discovering that was the main design constraint: the console declares the
// brand blue as `197 71% 42%` while everyone else writes `#208cb7`, and Infima
// wants a five-step ramp nobody else has. Generating per-vocabulary is what
// makes one source of truth actually possible.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { hexToHsl, hexToShadcnTriple, scaleLightness } from './color.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const tokens = JSON.parse(readFileSync(join(ROOT, 'tokens.json'), 'utf8'));

const v = (group, key) => tokens[group][key].value;
const HEADER = (what) =>
  `/* Copyright The DeviceChain Authors */\n` +
  `/* SPDX-License-Identifier: Apache-2.0 */\n\n` +
  `/*\n * GENERATED by tools/generate.mjs from tokens.json — DO NOT HAND-EDIT.\n` +
  ` *\n * ${what}\n */\n\n`;

/* ── Marketing / static vocabulary ─────────────────────────────────────── */

function brandCss() {
  const { core, surface, accents, type } = tokens;
  // Notes are prose and some run long. Wrap them rather than emitting a 140-col
  // line: this is the one generated file that gets COPIED INTO ANOTHER REPO and
  // read there by someone with no access to tokens.json, so the comment is the
  // only explanation they get.
  const wrap = (text, indent) => {
    const width = 76 - indent.length;
    const lines = [];
    let cur = '';
    for (const w of text.split(/\s+/)) {
      if (cur && (cur + ' ' + w).length > width) {
        lines.push(cur);
        cur = w;
      } else cur = cur ? cur + ' ' + w : w;
    }
    if (cur) lines.push(cur);
    return lines.map((l, i) => `${indent}${i === 0 ? '/* ' : '   '}${l}`).join('\n') + ' */\n';
  };
  const line = (name, value, note) =>
    (note ? wrap(note, '  ') : '') + `  --${name}: ${value};\n`;
  let out = HEADER(
    'Marketing + static-site vocabulary. Consumed by the public website and by\n' +
      ' * anything with no bundler: plain custom properties, hex values, no build step.\n' +
      ' *\n' +
      ' * This is the one output that is COPIED INTO ANOTHER REPOSITORY, so it names\n' +
      ' * its source in full: frontend/packages/brand/tokens.json in the devicechain\n' +
      ' * monorepo. Editing the copy is how the marketing site drifted onto a blue\n' +
      ' * neither the console nor the docs used. Change tokens.json and re-sync.'
  );
  out += ':root {\n';
  out += '  /* Core brand — sampled from the brandmark (branding/logo.svg). */\n';
  out += line('brand', core.primary.value);
  out += line('brand-bright', core.primaryBright.value);
  out += line('brand-deep', core.primaryDeep.value);
  out += line('brand-pale', core.primaryPale.value);
  out += '\n  /* Surfaces + text. */\n';
  out += line('bg', surface.bg.value);
  out += line('bg-deep', surface.bgDeep.value, surface.bgDeep.$note);
  out += line('ink', surface.ink.value);
  out += line('ink-2', surface.ink2.value);
  out += line('muted', surface.muted.value);
  out += '\n  /* Derived surface treatments. */\n';
  out += line('panel', 'rgba(255, 255, 255, 0.04)');
  out += line('border', 'rgba(122, 183, 217, 0.18)');
  out += line('rule', 'rgba(122, 183, 217, 0.16)');
  out += line('rule-strong', 'rgba(122, 183, 217, 0.34)');
  out += line('glow-strong', 'rgba(32, 140, 183, 0.25)');
  out += line('glow-soft', 'rgba(32, 140, 183, 0.12)');
  out +=
    '\n  /* Area accents. NEVER used for anything interactive — --brand alone\n' +
    '     carries that meaning. Order is pipeline order. */\n';
  for (const k of ['aqua', 'violet', 'magenta', 'amber']) {
    out += line(k, accents[k].value, accents[k].role);
  }
  out += '\n  /* Type stacks. */\n';
  out += line('sans', type.sans.value);
  out += line('mono', type.mono.value);
  out += '}\n';
  return out;
}

/* ── Console (shadcn / Tailwind) vocabulary ────────────────────────────── */

function shadcnCss() {
  const { core } = tokens;
  let out = HEADER(
    'Console vocabulary. Values are BARE `H S% L%` triples with no hsl() wrapper,\n' +
      ' * because shadcn composes them as `hsl(var(--primary) / <alpha>)` — wrapping\n' +
      ' * them here would silently break every alpha variant.\n' +
      ' *\n' +
      ' * Scope: every token whose value is DETERMINED BY the brand blue — the blue\n' +
      ' * itself wherever shadcn names it, plus the foreground that has to read on\n' +
      ' * top of it. A consumer keeps ownership of everything else in its scale\n' +
      ' * (background, card, popover, chart-*, and the non-primary sidebar-*).'
  );
  const block = (sel, hex) => {
    const t = hexToShadcnTriple(hex);
    return (
      `${sel} {\n` +
      `  --primary: ${t};\n` +
      '  --primary-foreground: 0 0% 100%;\n' +
      `  --ring: ${t};\n` +
      `  --sidebar-primary: ${t};\n` +
      '  --sidebar-primary-foreground: 0 0% 100%;\n' +
      `  --sidebar-ring: ${t};\n` +
      '}\n'
    );
  };
  out += block(':root', core.primary.value);
  out += '\n';
  out += block('.dark', core.primaryBright.value);
  return out;
}

/* ── Docs (Docusaurus / Infima) vocabulary ─────────────────────────────── */

function infimaCss() {
  const { core } = tokens;
  // Infima wants a six-step ramp around primary, and it is built by scaling
  // LIGHTNESS in HSL — hue and saturation are held constant. The factors below
  // are Docusaurus's own conventional steps.
  //
  // Do not "simplify" this to an RGB mix toward white/black. That adds white to
  // all three channels equally and therefore desaturates: checked against the
  // docs site's existing ramp, a mix-to-white `lightest` landed at 51.5%
  // saturation against the correct 71.1% — a visibly greyer, washed-out blue.
  const ramp = (base) => ({
    darkest: scaleLightness(base, 0.7),
    darker: scaleLightness(base, 0.85),
    dark: scaleLightness(base, 0.9),
    base,
    light: scaleLightness(base, 1.1),
    lighter: scaleLightness(base, 1.15),
    lightest: scaleLightness(base, 1.3),
  });
  const emit = (sel, base) => {
    const r = ramp(base);
    let s = `${sel} {\n`;
    s += `  --ifm-color-primary: ${r.base};\n`;
    s += `  --ifm-color-primary-dark: ${r.dark};\n`;
    s += `  --ifm-color-primary-darker: ${r.darker};\n`;
    s += `  --ifm-color-primary-darkest: ${r.darkest};\n`;
    s += `  --ifm-color-primary-light: ${r.light};\n`;
    s += `  --ifm-color-primary-lighter: ${r.lighter};\n`;
    s += `  --ifm-color-primary-lightest: ${r.lightest};\n`;
    s += '}\n';
    return s;
  };
  let out = HEADER(
    'Docs vocabulary (Docusaurus/Infima). Infima needs a five-step ramp either\n' +
      ' * side of primary; it is generated from the single canonical value so the\n' +
      ' * steps cannot drift out of order.\n' +
      ' *\n' +
      ' * Brand colours only — the docs site owns its own background/surface theming.'
  );
  out += emit(':root', tokens.core.primary.value);
  out += '\n';
  out += emit("[data-theme='dark']", core.primaryBright.value);
  return out;
}

/* ── JSON, for anything that would rather read data than parse CSS ─────── */

function flatJson() {
  const flat = {};
  for (const [group, entries] of Object.entries(tokens)) {
    if (group.startsWith('$')) continue;
    for (const [key, def] of Object.entries(entries)) {
      if (key.startsWith('$')) continue;
      flat[`${group}.${key}`] = def.value;
    }
  }
  const derived = {};
  for (const k of ['primary', 'primaryBright', 'primaryDeep', 'primaryPale']) {
    derived[k] = {
      hex: tokens.core[k].value,
      hsl: hexToHsl(tokens.core[k].value),
      shadcn: hexToShadcnTriple(tokens.core[k].value),
    };
  }
  return JSON.stringify({ flat, derived }, null, 2) + '\n';
}

/* ── Drive ─────────────────────────────────────────────────────────────── */

const OUTPUTS = [
  ['css/brand.css', brandCss()],
  ['css/shadcn.css', shadcnCss()],
  ['css/infima.css', infimaCss()],
  ['tokens.generated.json', flatJson()],
];

const check = process.argv.includes('--check');
let stale = [];

mkdirSync(join(ROOT, 'css'), { recursive: true });
for (const [rel, content] of OUTPUTS) {
  const path = join(ROOT, rel);
  if (check) {
    let existing = null;
    try {
      existing = readFileSync(path, 'utf8');
    } catch {
      /* missing counts as stale */
    }
    if (existing !== content) stale.push(rel);
  } else {
    writeFileSync(path, content, 'utf8');
    console.log(`wrote ${rel}`);
  }
}

if (check) {
  if (stale.length) {
    console.error(
      `error: generated files are stale or missing:\n  ${stale.join('\n  ')}\n` +
        `Run \`npm run generate -w @devicechain/brand\` and commit the result.`
    );
    process.exit(1);
  }
  console.log('generated files are up to date');
}
