// Copyright The DeviceChain Authors
// SPDX-License-Identifier: Apache-2.0

package model

import (
	"bytes"
	"encoding/json"
	"os"
	"testing"
)

// The command-status WIRE vocabulary the sim's load-test harness mirrors, held to the
// enum that owns it.
//
// dc-simulator cannot import this module — it is deliberately an untrusted external
// client of the platform — so the harness spells QUEUED / SENT / SUCCESSFUL as its own
// literals and compares durable command rows against them.
//
// 🔴 THE HAZARD IS A PASSING ORACLE, NOT A BREAKING ONE. The command round-trip gate
// asserts that every planted command reached SUCCESSFUL and that none was left stranded
// in QUEUED/SENT. Rename a status on this side and the harness's copy does not error —
// it stops being able to match. "None stranded in QUEUED" becomes trivially true, and a
// run in which every command was in fact stranded reports the invariant satisfied.
//
// The fixture is generated by the sim from the same constants the harness compares with
// (backend/sims/dc-simulator/loadtest/authored_rules_fixture_test.go, which carries the
// staleness gate).

const authoredSimFixturePath = "../../../testdata/authored-rules/authored-rules.json"

// authoredSimFixture declares the whole file because the decode below fails closed.
// Only commandStatus is this module's to judge; the other sections are read by the
// modules that own them (device-management for alarms, event-processing for rules) and
// are deliberately left unjudged here rather than silently tolerated.
type authoredSimFixture struct {
	Rules          json.RawMessage `json:"rules"`
	WireVocabulary struct {
		AlarmState    json.RawMessage `json:"alarmState"`
		CommandStatus struct {
			Queued     string `json:"queued"`
			Sent       string `json:"sent"`
			Successful string `json:"successful"`
		} `json:"commandStatus"`
		DetectionRuleStatus json.RawMessage `json:"detectionRuleStatus"`
	} `json:"wireVocabulary"`
}

// TestAuthoredSimCommandStatusesAreRealStatuses holds each mirrored literal to the real
// CommandStatus enum, by identity — not merely by Valid(), which a DIFFERENT valid
// status would also satisfy. A harness comparing SENT where it meant SUCCESSFUL is
// asking a well-formed question about the wrong thing.
func TestAuthoredSimCommandStatusesAreRealStatuses(t *testing.T) {
	raw, err := os.ReadFile(authoredSimFixturePath)
	if err != nil {
		t.Fatalf("read %s: %v\n\nThis fixture is the ONLY thing tying the load-test harness's "+
			"mirrored command statuses to this module's enum. If it moved, re-point this test "+
			"rather than deleting it; regenerate it with:\n  cd backend/sims/dc-simulator && "+
			"go test ./loadtest/ -run TestAuthoredRuleFixtureIsCurrent -update-rule-fixture",
			authoredSimFixturePath, err)
	}
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	var fixture authoredSimFixture
	if err := dec.Decode(&fixture); err != nil {
		t.Fatalf("decode %s: %v (a field added on the producing side must be mirrored here, "+
			"not ignored)", authoredSimFixturePath, err)
	}

	// Identity against the declared constant, not merely Valid(): a DIFFERENT valid status
	// would satisfy Valid() while the harness asked a well-formed question about the wrong
	// thing. Identity implies validity, and the one case it would not — a status declared
	// but dropped from Valid() — is already pinned by TestCommandStatusValid in this package.
	mirrored := fixture.WireVocabulary.CommandStatus
	for _, c := range []struct {
		name string
		got  string
		want CommandStatus
	}{
		{"queued", mirrored.Queued, CommandQueued},
		{"sent", mirrored.Sent, CommandSent},
		{"successful", mirrored.Successful, CommandSuccessful},
	} {
		// Negative control: an empty value compares equal to nothing, so without this a
		// missing section would sail through as three silent non-matches.
		if c.got == "" {
			t.Errorf("the fixture carries no %s status, so this check has nothing to hold to "+
				"the real enum", c.name)
			continue
		}
		if CommandStatus(c.got) != c.want {
			t.Errorf("the load-test harness compares against %s status %q, but this module "+
				"writes %q — the harness's comparison can never match, so its "+
				"'no command stranded' invariant becomes trivially true and PASSES over a run "+
				"in which every command was stranded", c.name, c.got, c.want)
		}
	}

	// The harness treats SUCCESSFUL as the settled terminal of a round trip and
	// QUEUED/SENT as in-flight. If that ever stopped being true here, the gate would be
	// waiting for a state that is not an end state, or reporting stranded commands that
	// had in fact finished.
	if !CommandSuccessful.Terminal() {
		t.Error("SUCCESSFUL is no longer terminal, but the harness waits on it as the settled " +
			"end of a command round trip")
	}
	if CommandQueued.Terminal() || CommandSent.Terminal() {
		t.Error("QUEUED/SENT are now terminal, but the harness reports a command left in " +
			"either as stranded in flight")
	}
}
